### ISSUE TITLE
Physical backspace key is slow

### ISSUE THREAD

**Issue by TomJansen** [sspanak/tt9#123]
when remaping the backspace to a physical key, the responsiveness is much lower then when using the software backspace button. Can this responsiveness be improved somehow?

**Comment by sspanak** [comment]
I think I know what you mean. Unfortunately, I can't make them work the same on all phones, because the on-screen key needs to be adjusted programmatically, while the keypad repeat rate is handled by Android and it will probably differ a little on every phone.

Either way, I am almost certain there is a mistake in the code, slowing down the hardware key more than it should, that I will fix.

Technical Description:
The on-screen key sends events so fast, that I had to write extra code to make it repeat every 100 ms or so. Unfortunately, I forgot the hardware keys have a normal repeat rate and additionally applied the software repeat rate to the hardware backspace. When the two are combined, it results in a longer delay between two "delete" events.

Solution:
Apply the repeat delay only to the soft key.

**Comment by sspanak** [comment]
Thanks for reporting! I wouldn't have noticed it myself.

**Comment by sspanak** [comment]
The hardware key is no longer manually controlled, so it will now repeat at whatever the default phone/Android rate is. On my phone the delay between two events is about 50 ms. I adjusted the soft key to match that. It may differ on other phones, but nothing can be done about it. Case closed.
