### ISSUE TITLE
Proposal: use dictionaries with already defined frequencies

### ISSUE THREAD

**Issue by TomJansen** [sspanak/tt9#124]
When using the dictionaries now, the frequency is not yet set for the words. This means that it will take significant time before that more-frequently used words appear first in the suggestions list for each language.

A possible solution is to use the AOSP dictionary files [here](https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/master/dictionaries). These already have a frequency count built-in for each word. In addition, these dictionaries are kinda the standard as it goes for custom keyboards, like AnySoftKeyboard and Florisboard. This means more predictable behavior and less weird/wrong words.

In addition, the use of these dictionaries could improve speed. The idea is for the compiler to convert these AOSP dictionary XML files to .sql at compile-time. This means they would only have to be activated when the user selects the language, instead of being converted and imported to sql on the device itself, saving a lot of time for the user. Maybe in combination with #53?

**Comment by sspanak** [comment]
Even now the dictionaries are in CSV format, it's just they have a single value per row. So, it is not so difficult to "upgrade" the format and use `word,frequency`, instead of just `word`.

I agree that the AOSP dictionaries may be of higher quality, containing less nonsense words, but I don't believe priorities will change the game that much.

Have in mind T9 predictions are very different from QWERTY predictions. For example, if you wanted to type `fondly`, in QWERTY mode you would want suggestions that are similar to `fo`, `fond` and finally, `fondly`. 

But in T9, you always type numbers and get predictions for the given number sequence. So, for `466359 (fondly)`, you would get `do (46)` and `FM (46)`; `food (4663)`, `gone (4663)`, `done (4663)`, `fond (4663)`; finally, you will get to `fondly`. As you see, no matter the priority, you will always get completely different suggestions, until you get closer to the word you have in mind, because it is most important to match the sequence and then order them by priority. So, yes, predefined priorities may help a little, but don't expect mircales.

If I have enough free time, I may experiment and see if there is a significant benefit, but for now I don't feel like it is worth the effort.

**Comment by sspanak** [comment]
Out of curiosity, I ran some benchmarks. It turned out converting the words to digit sequences actually takes significant amount of time. 

Here are some test results:
```
// Read "en-utf8":
// (Read the file without doing anything else)
I/tt9.DictionaryLoader.importAll: Dictionary: 'en-utf8.txt' processing time: <130 ms

// Read "en-utf8" + validateWord():
// (Read the file and validate the words)
I/tt9.DictionaryLoader.importAll: Dictionary: 'en-utf8.txt' processing time: ~130 ms

// Read "en-utf8" + validateWord() + ArrayList management:
// (Read the file, validate the words and build ArrayLists to be inserted in the database, but do not insert them)
I/tt9.DictionaryLoader.importAll: Dictionary: 'en-utf8.txt' processing time: ~150 ms

// Read "en-utf8" + validateWord() + ArrayList management + getDigitSequenceForWord():
// (Same as the above, but convert the words to digit sequences. e.g. "food" -> "3664")
I/tt9.DictionaryLoader.importAll: Dictionary: 'en-utf8.txt' processing time: 6.3 s

// Read "en-utf8" + validateWord() + ArrayList management + getDigitSequenceForWord() + DictionaryDb.insertWordsSync():
// (Same as the above, but insert the data. This is how the importer works today)
I/tt9.DictionaryLoader.importAll: Dictionary: 'en-utf8.txt' processing time: 11.3 s

// Read "en-utf8" + validateWord() + ArrayList management + DictionaryDb.insertWordsSync():
// (Normal inserting, but as if the sequences are pre-generated at build time)
I/tt9.DictionaryLoader.importAll: Dictionary: 'en-utf8.txt' processing time: 4.6 s
```

Test Conditions:
- TT9 v11.0, debug build
- Device: Qin F21 Pro+ (no Google)
- The charger is plugged in.
- The screen stays on during the test.
- The Settings screen is on during the test. No scrolling or other interaction.
- There are no toast messages during the test.
- Results are the average of 3 test runs. The database is truncated before each run.

This means, if sequences are pre-generated at build time, dictionary importing could become more than 2 times faster. However, the dictionary files would become 2 times bigger.

**Comment by sspanak** [comment]
After additionally researching, it turned out it is not possible to directly use the AOSP dictionaries, because they contain repeating words (e.g. "i've" and "I've"), but TT9 requires unique words in the database to work properly.

However, having predefined frequencies definitely appears to be beneficial, despite the predictions working differently in T9 mode.

So, in order to implement this task, do the following:

1. Enable dictionaries in CSV format.
   - There is no header
   - Rows are in the format: `String(tab)Integer`
   - `String` is the word
   - `Integer` must be a non-negative integer and is the frequency
   - `Integer` is optional. If missing it is assumed to be 0.
2. Validate the CSV when building.
3. Change the `DictionaryLoader` to support the new dictionary format.
4. Similar to the `capitalize-dictionary-words.js` script create a script for injecting the priorities. Repeated words or multiple runs would overwrite the priority, if already set.
