### ISSUE TITLE
Custom keyboard button mapping (for use on a computer)

### ISSUE THREAD

**Issue by ajiekc905** [sspanak/tt9#126]
Can we have a way to add / use redefined button / letter mapping? (Just for letters, not for *, # ...)
Thanks.

**Comment by sspanak** [comment]
I am not sure I understand the question.

**(Option A)** If you are asking if it is possible to swap number keys, say 1 and 3; 9 and 4; etc..., the answer is: currently, the number keys can not be configured, but it is definitely doable.

Roughly, it would require:
- Adding new preference items for each key:
  - in `SettingsStore`
  - on the Settings screen (with proper validation of conflicting keys). Also, default values must be ensured the first time the screen is displayed.
  - However, the Settings screen may become too big, so it may be a good idea to create a separate screen, just for the hotkeys.
- Modifying `KeyPadHandler.keyCodeToKeyNumber()` to return the remapped number for each key, instead of the hardcoded numbers.
- Ensuring default values the first time `TraditionalT9` runs.

**(Option B)** If you would like to assign completely different letters to each number key, the answer is: it is possible by adding a custom language with the desired keypad layout, but the configuration would stay permanent. 

Word predictions are tightly coupled with the matching digit-letter pairs, so it is not possible to change them dynamically without redesigning the entire application (if at all).

**Comment by ajiekc905** [comment]
It is option B. Word prediction can be compiled externally ex on a computer/ laptop.

**Comment by sspanak** [comment]
I see. Well, in this case I would recommend looking for a word prediction engine, not an entire application like this one. 

The engine here is coupled with the Android Input Service, RoomDB (the database API) and SharedPreferences (the settings storage API), making it quite efficient on a phone. But building and running the code on a computer would be a challenge.

I suppose you could reuse the `TraditionalT9` and the `InputMode` classes with minimal changes, but you would have to take care of the keyboard input and the storage management on your own. And I can't help with that. It is too different from what I am doing.

**Comment by sspanak** [comment]
I have updated the title to make it more clear what this question is about. I hope you don't mind.
