### ISSUE TITLE
Return caret with double press zero

### ISSUE THREAD

**Issue by postpersonality** [sspanak/tt9#135]
Currenty in order to enter return caret I need to press 3 keys: zero-down-ok.
It would be nice to have a shortcut.

**Comment by sspanak** [comment]
Now, this may be problematic. Personally, I find your suggestion confusing and I don't want it to work this way. I'd rather type spaces when pressing 0-key repeatedly, instead of newlines.

I guess this can be solved by adding a setting for repeated 0-key presses. For example, there could be a dropdown to choose between space, newline or a dot (I know some people prefer that).
