### ISSUE TITLE
Option to double (triple, ...) click same button to iterate over character

### ISSUE THREAD

**Issue by nebkrid** [sspanak/tt9#140]
Hi,
I would prefer to have an option to enabling iterating over the character instead of entering it twice. I know that this of course breaks the idea of word predicition, however another perspective is to "free it" from the saved word (so if you expected that the word is not within the dictionary you can directly start to enter it without predection. 
In order to enter a letter twice a small delay or something like this could be watched by the application to proceed to next letter.
Background: I already tried your app successfully* on an Android TV and want to use the standard remote which has a numpad to avoid iterating. Because here entering only keywords is enough most, less effort of predicition is needed but avoiding multiple clicks.

*some more optimization should be done for easyness Android TV and I am happy to support programmind and testing (hope you are interested in this too?). But first step by step and I think this feature, which is even helpful for others too, might be quite easy to add?

Generally: Thanks for your app! I couldn't find such an app in the play store although I am wondering that none other TV user is interested / missing this but enters letters with a soft keyboard and the d-pad of the remote...

**Comment by sspanak** [comment]
Have you tried using ABC mode, instead of Predictive? In ABC mode, pressing a number key indeed cycles the possible letters and there is no prediction. I guess, this is what you are looking for... ?

Alternatively, TT9 provides more sophisticated ways of typing words that are not in the dictionary or words that are similar to existing dictionary words. For example, you could type "Anakin", by starting of with "Ana", then using the right arrow to keep adding letters to the word stem. See the advanced typing rules [in the manual](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#d-pad-right-).

As for your other question: sorry, no, I do not plan to support TV sets. These devices are of little interest to me. I don't even have one. However, any pull requests are welcome. I didn't quite get what optimizations you have in mind, but as long as they don't change the experience on a phone, they should be OK.

**Comment by nebkrid** [comment]
Oh, thank you for pointing me to this option! This was exactly what I am looking for. I thought "input mode" means "input method" - so to change back to e.g. the native soft keyboard. And because I thought I found all options in the settings, I didn't looked for a manual... Sorry for bothering you.
Just as an idea, not sure whether it is useful in praxis: Did you thought about a "mixed mode"? So ABC mode for input, but offering prediction, too, in order to shorten longer input. 

Regarding TV: No worries. Then I will play around with a fork and try not to change the behaviour of phone. Some thoughts I have are to use the bigger screen to show more options (or even the 3x4 main input buttons for learning which letter is on which button) and especially to offer more/other buttons for the hotkeys (e.g. I don't have a "#" or "*" or any "F" buttons on the remote)

**Comment by sspanak** [comment]
> Oh, thank you for pointing me to this option! This was exactly what I am looking for. I thought "input mode" means "input method" - so to change back to e.g. the native soft keyboard. And because I thought I found all options in the settings, I didn't looked for a manual... Sorry for bothering you.

I understand. As a programmer, I never read the manual myself.

> So ABC mode for input, but offering prediction, too, in order to shorten longer input.

This is not possible, unless I completely change the way the application works. By design, keyboards have a single suggestion list. I am using it either for displaying the words in Predictive mode or displaying the letters in ABC mode. In order to display both letters and words, there would have to be a secondary list and each has to rewired depending on the item source.

Anyway, I find it difficult to appreciate the idea. I mean, T9 is meant to reduce the key presses to 1 per letter. However, typing in that "mixed" mode you suggest, one would still need to press a single key multiple times to select the desired letters, which kind of defeats the purpose of T9 and suggestions. Having 17 years of experience with barphones, I definitely feel how input is going to take longer, not shorter. Perhaps, the experience with a remote control is different... I don't know... it makes me scratch my head... :thinking: 

>  Some thoughts I have are to use the bigger screen to show more options (or even the 3x4 main input buttons for learning which letter is on which button)

I do want to create a full touchscreen version of TT9 and make it usable on a smartphone, because this is the typing method for thumbs, while QWERTY is for 10 fingers. Unfortunately, with my skills, it would take at least a month and I don't have that much free time now. 

> ... offer more/other buttons for the hotkeys (e.g. I don't have a "#" or "*" or any "F" buttons on the remote)

Extra key support is not a bad idea. I just don't have the device to verify them. 

In order to add new ones, you need to add them to the beginning `SectionKeymap.java`. It's the file that takes care of the entire key settings section. Do any validation in the same file as needed. Also, if you need to override the defaults, you can do it in: `SettingsStore.setDefaultKeys()`.

However, you may want for PR #141, because it fixes some bugs with key handling and also introduces some changes in that particular file. You'd probably want to avoid code conflicts...

**Comment by nebkrid** [comment]
> Having 17 years of experience with barphones, I definitely feel how input is going to take longer, not shorter. Perhaps, the experience with a remote control is different

I am absolutley convinced that an experienced user is way faster with true T9 than a "mixed" mode and I don't think that a remote will change this dramatically. It's just the different usecase and that saving new custom words is always more complicate, so for a TV I think it's not worth (a user will most times search only once for a movie title and on the other hand in movie titles will often be unknown words). Actually my wording for the "mixed" mode was not perfect and maybe misleading: I didn't mean suggestion like in T9, but additional auto-completion hints to shorten up long words (like in the advanced filtering for predicition mode), which can be chosen with right arrow. But well, if it's complicate to implement: As I wrote, just an idea to have in mind as another option :)

> I do want to create a full touchscreen version of TT9 and make it usable on a smartphone, because this is the typing method for thumbs, while QWERTY is for 10 fingers. Unfortunately, with my skills, it would take at least a month and I don't have that much free time now.

Ok, then I will try my luck, and hope that an IME is not completley different than other android apps regarding GUI. I will let you know when I get it working. But may take some time, too...

> In order to add new ones, you need to add them to the beginning SectionKeymap.java...

Thank you for your hints!

**Comment by sspanak** [comment]
>  I didn't mean suggestion like in T9, but additional auto-completion hints to shorten up long words (like in the advanced filtering for predicition mode), which can be chosen with right arrow. But well, if it's complicate to implement: As I wrote, just an idea to have in mind as another option :)

This is currently not possible. ABC mode does not use the database, so it cannot provide any other suggestions but the letters. In order to achieve what you are describing, [ModeABC](https://github.com/sspanak/tt9/blob/master/src/io/github/sspanak/tt9/ime/modes/ModeABC.java) has to be refactored to query the database like [ModePredictive](https://github.com/sspanak/tt9/blob/master/src/io/github/sspanak/tt9/ime/modes/ModePredictive.java). Or even better, use it as a base to create a new "hybrid" or "mixed" mode. 

Still, I can't really wrap my head around this intermediate scenario. You can either type letter by letter or type entire words. I hope you can complete what you have in mind. I would be curious to see it.
