### ISSUE TITLE
Add back User Dictionary

### ISSUE THREAD

**Issue by justbruce** [sspanak/tt9#153]
I miss the 'user dictionary' functionality from Clam's version - having TT9 learn MY most-used words over time and place them first in the word list was super useful to me - any chance of it returning?

  I've started digging into the code but there seems to have been enough refactoring that I'm having trouble tracking where this functionality is best inserted.

**Comment by sspanak** [comment]
But learning is still there, I haven't removed it. Try typing something, for example "4663" in English, then select the last suggestion (let's say it is "hoof"). Now press OK or 0-key to accept it. Type "4663" again and you'll see "hoof" is the first suggestion in the list.

The "user dictionary" had nothing to do with the learning functionality. It was used to import your own list of words and use it instead of or together with the factory dictionary. But I don't plan to restore that.

**Comment by justbruce** [comment]
You're correct, except the punctuation doesn't do learning.

User Dictionary used to let you save/load. 

Is there any way to save the dictionary[with added words] and/or learned priority? I use 2 phones and it would be nice to transfer the dictionary back and forth as needed.

**Comment by sspanak** [comment]
> On the learning -You're correct, except the punctuation doesn't do learning. I'd really like the period [.], the question mark [?] and the exclamation point[!] to come before the comma. I kinda jumped the gun when the punctuation didn't update as I worked.

This is not going to change, sorry. Punctuation marks are arranged based on usage frequency, so changing the order will actually result in more clicks. And I've made sure `?` and `!` are quickly accessible. Instead of going forward through the entire list, you could go back and select them. They are one and two positions away from the start, respectively.

> Is there any way to save the dictionary[with added words] and/or learned priority? I use 2 phones and it would be nice to transfer the dictionary back and forth as needed.

No, there isn't a way at the moment. 

I am not strictly against that feature and I may do it, but I don't see it happening in the near future. However, when version 16 comes out, it will include word priorities out-of-the-box and predictions will be much more efficient. You wouldn't have to worry about all this. 

And as for the custom added words, yes, you would still have to add them manually for now. It is what it is.
