### ISSUE TITLE
Back button stopped functioning in Predictive mode

### ISSUE THREAD

**Issue by justbruce** [sspanak/tt9#154]
Phone is a Cat S22 Flip
With upgrade to V15.0, the back button refuses to function unless I tap the input mode [#] button to switch to another input mode.

Does not happen with ABC or 123 modes

**Comment by sspanak** [comment]
I am unable to reproduce it on my phone. I have a couple of questions that could help me investigate:
- Does it happen in all applications or in a particular one? Please, try the SMS app, if you haven't.
- Does it happen if you reassign the backspace key?
- Do you use more than one language? If yes, does it happen only _after_ you have changed the language? For example, go to a text field, type something, then delete it. Then type something, change the language and try deleting the text. If backspace works properly in the first case, but it doesn't in the last one, this is a known bug and it will be fixed in the next release.

**Comment by justbruce** [comment]
All applications tested. [Signal Private Messenger, Notepad Free, Firefox, Chrome,Messages]

It does happen even if Backspace=Delete. [I don't have a menu button so I cannot test that value]

I do not use more than one language.  English is the only one active

To be clear, it isn't Backspace that isn't working, its the BACK button.  If I'm trying to go back to the message list once I'm done typing by pressing BACK, nothing happens if I'm in Predictive. 

The DPAD-Left and DPAD-Right keys also don't work for moving the cursor when Predictive is active.

 Also [since it may be related] the center of the DPAD [what I think of as Enter or OK] fails to select a word or letter in any Input Mode.  It does nothing when TT9 is active

**Comment by sspanak** [comment]
What you say is really strange, because the BACK key is handled the same way in all modes. I really see no reason why would it not work in Predictive only. And, on top of that, I have not touched the code that takes care of it in v15, neither have I changed OK, LEFT or RIGHT.

I'll double check the code, but this problem may be tricky. Do you mind if I build a testing version for you? It would display some informational messages that will hopefully help me understand what is going on.

> To be clear, it isn't Backspace that isn't working, its the BACK button

Got it. Thanks for clearing that out.

**Comment by amccannv** [comment]
I have some similar problems that may either help or harm your debugging process. I am trying to use this on a ZTE Cymbal 2.

When there is no text at all, the back key does not function to go back to my messages - for this reason I am not able to go back in normal circumstances. I have set the backspace key as my back/delete button to mimic the much poorer IME that comes default on the Cymbal, but it occurs with any button I map. In order to overcome this, I could change input mode to numeric or alphabet and type one character, D-PAD left to reach the start of the text body and the back button functions correctly - this is to say, I can only go back if there is some text and I can only press the D-PAD once to navigate back. I can not erase all text and press it again, it becomes the same issue as my first sentence. Part of this may be overcome with your fix in #157.

I also loose access to my right soft key (as I call it), which is the uppermost right button which should bring up some messages options on my phone (discard, saves as draft, etc.).

Otherwise this is working very well, and I hope to continue to use it if these problems can be solved.

If you need any more information or I could make my explanation clearer, I am happy to provide.

**Comment by sspanak** [comment]
Thanks for the additional feedback! I've managed to reproduce it on my phone when I assigned the CALL button to the Backspace function. And exactly, only the Numeric mode works properly.

I think I have an idea what may be wrong and I don't need more information at the moment. But please, stay tuned, I may have additional questions in the next few days.

Meanwhile, I would appreciate a screenshot or two, showing the situation when you are stuck. I would like to see what you see.

**Comment by sspanak** [comment]
@amccannv, @justbruce, I created a beta release that fixes the keys not working. You can find it [here](https://github.com/sspanak/tt9/releases/tag/beta-15.1).

Please try it out and let me know if it fixes the problem(s) for you. It works fine on my phone, but there may be something specific on yours.

**Comment by amccannv** [comment]
Confirming the changes are working as intended on my ZTE Cymbal 2.

**Comment by justbruce** [comment]
I'd consider this bug squashed.  I've been using this version for the last 36 hours and no odd behaviour.

Thanks, @sspanak
