### ISSUE TITLE
Fix double-0 hotkey bug

### ISSUE THREAD

**Issue by qascot** [sspanak/tt9#158]
Double-0 hotkey has two bugs. It adds space before action, so space between word and dot looks strange. Second - double-0 action repeats after every single 0 press until another button pressed.
Maybe it's better to add Double-click timer for this function?

**Comment by sspanak** [comment]
It is supposed to insert the selecter character when pressed more than once. I guess it is bad wording and it should be renamed to `Character for 0-key Multiple Press` instead of `... Double Press`.

However, I didn't get the first one. What do you mean "it adds space before action"? What action? And what do you mean by strange space?

**Comment by qascot** [comment]
While typing in T9 mode double press 0 first adds " " and only then add symbol specified in settings "." or "\n". So text looks like this: "Text ." 
Or like this: "Text_
"
(I put underline here instead of " " to show where it is.)

**Comment by sspanak** [comment]
I see. Short answer is: it is working as intended. 

Explanation: You see, this setting is for the character when you press 0-key _more than once_, not once. If you press it once, you are presented with a list of suggestions and it will type the one you pick. Repeated pressing will type the character selected in the settings.

I hope this makes it clear.

**Comment by qascot** [comment]
OK. Thanks for the explanation.

**Comment by justbruce** [comment]
I'd agree that the expected usage [because old TT9 by Clam did it this way.  Also, standard touch keyboards from Apple, Samsung, and Google do it this way] is that double pressing zero would insert

1.Backspace
2.[Selected character] (i.e. the newline or period]
3. A space 

 This makes properly ending a sentence or paragraph a much quicker, easier set of keystrokes [keeps your fingers on the lower 12 keys rather than having to reach up to the DPAD] which is why I thought the setting was added to Old Skool TT9.
