### ISSUE TITLE
Basic Punctuation Suggestions Not Offered On '1'-Key Press After Commonly Contracted Words

### ISSUE THREAD

**Issue by levone1** [sspanak/tt9#187]
When pressing the '1' key while a word suggestion is highlighted, there are a number of suggestions presented which show common punctuation, if you want to add a period or comma, etc., after the word.  This behavior is missing if the word that's highlighted is one which is commonly contracted, like "you", (you'll, you're, etc.), or "do", (don't).  In those cases, only the common contraction suggestions are shown, not the punctuation suggestions.

Thanks

**Comment by levone1** [comment]
Maybe best if the contractions were just part of the regular word suggestions, like if you type "can", then "can't" would just show in the regular suggestion list, and pressing '1' would only be for punctuation...?

**Comment by AF1512** [comment]
That might be better, so you can also type "dont" and get "don't" (instead of "foot").

**Comment by louisabraham** [comment]
I was going to open this issue. I think indeed that there are two ways to handle this: storing the contracted words with or without the key 1. I think that storing them with 1 might make the dictionnary more efficient since it adds information at input time.

**Comment by sspanak** [comment]
> That might be better, so you can also type "dont" and get "don't" (instead of "foot").

You are pressing the wrong keys to type "don't".  Instead of "3668", use "3661" to get the correct suggestion. :slightly_smiling_face: 

I realize it's a habit caused by using touchscreen keyboards and they do offer such shortcuts for a reason, because the apostrophe is difficult to access, unlike in T9; and because of swipe typing. But typing using physical keys is different and happens under different set of rules.

So, I will fix the problem with the missing suggestions:
- Typing `you'`, should bring up all variants that end with a punctuation mark. There is definitely a bug.
- Typing `you`, should bring up `you're` or `you'd`, but sometimes they are missing. There may be something wrong or it may be because of the learned word priority on my phone. Either way, I'll check.

But I will not:
- Add "shortcut" words, for example: `dont` that auto-converts to `don't`. This will not reduce the key presses, therefore it has no value for T9 typing.
- Exclude 1-key from typing contractions. In Dutch language, for example, there are words that start with an apostrophe: `'s-Graveland` or `'t`. If 1-key types only punctuation, they will never appear as suggestions and it would be impossible to type them (except letter by letter). It will also cause other techincal problems, so it is completely out of the question.

**Comment by louisabraham** [comment]
> You are pressing the wrong keys to type "don't". Instead of "3668", use "3661" to get the correct suggestion. 🙂

Oh it works! I guess I did it wrong the first time.

**Comment by sspanak** [comment]
> the problem is actually that the french dictionnary doesn't include article contractions, eg l'ordinateur.

Yes, unfortunately, French dictionary is not nearly as good as English. It has no contractions, it is missing proper capitalization, countries, cities and whatnot. If you know a good, spell-checked French word list source, I would be happy to include it in TT9. You are also welcome to open a PR, if you feel like contributing.

And it's the same for German and Italian (I guess). I don't speak all the supported languages, which makes it very difficult for me to find high quality dictionaries. Any help with that will be much appreciated.

For now, the best I can do is fix the obvious bugs in the code...

**Comment by sspanak** [comment]
> I've noticed improvement on this in general in recent versions.

Actually, there is no improvement. The problem has always existed only for some words.

I agree this is annoying in English and probably makes French and Italian nearly unusable, so it must be fixed. The good news is, after playing a bit with my old Nokia, I have a good idea how to fix it. The bad news is, it looks like a big piece of work, so I am postponing it until I have more free time.
