### ISSUE TITLE
Dialer on LG Classic Flip inputs letters not numbers

### ISSUE THREAD

**Issue by DarthFlip** [sspanak/tt9#216]
On the LG Classic Flip (L125) when I start typing to make a call the dialer types the first number then starts typing letters. What information can I provide to help with this issue?

**Comment by sspanak** [comment]
First, I need to know if you see the status icon on top (the one that shows whether you are typing letters or numbers), and if you can change the input mode as if you were typing in a regular text field.

**Comment by sspanak** [comment]
Some more questions:
1. The phone must have Contacts (or Phonebook, or whatever it is called). Is it possible to enter a phone number normally there?
2. Does the phone number contain special characters - `#`, `*` or `+`?
3. Does TT9 fail with only one phone number or with all?

**Comment by DarthFlip** [comment]
When making a new contact by the number field it works normally and switches automatically to number input. When searching in the contact app it searches with letters.
The keypad does have a `*` and `#`, when you long click the `*` it makes a `+` on the built in ime.
When on the main launcher screen and I click a number it automatically opens the dialer, and inputs the first number that I clicked into the dialer. Once I start typing it switches to whatever input mode tt9 is in.

**Comment by DarthFlip** [comment]
It seems like the dialer is part of the contacts app on this phone, `com.android.contacts/com.android.contacts.DialtactsActivity` is the activity that seems to be running when I am on the dialer screen.

**Comment by sspanak** [comment]
I may have been detecting the dialer field incorrectly. Could you please try if [this .apk](https://github.com/sspanak/tt9/releases/download/testing/tt9-v19.2+dialer-fix.apk) fixes the problem?

**Comment by DarthFlip** [comment]
Thank you for working on it! But the change did not fix the issue.

**Comment by sspanak** [comment]
> Thank you for working on it! But the change did not fix the issue.

How unfortunate... :cry:

This means, the dialer field is non-standard and `InputType.isDialer()` fails to recognize it.

I see you have some techincal knowledge. Would it be possible for you to check the metadata of the dialer input? I need the `inputType` and `packageName` properties. If not, I can build an APK that prints the degugging information for you.

**Comment by DarthFlip** [comment]
> It seems like the dialer is part of the contacts app on this phone, `com.android.contacts/com.android.contacts.DialtactsActivity` is the activity that seems to be running when I am on the dialer screen.

That is the package name. The phone doesnt have a com.android.dialer package. I am trying to get input type but I am having issues, do you have an adb command I cun run? I was trying logcat and dumpsys with grep but couldnt seem to find it that way.

**Comment by DarthFlip** [comment]
So I get 2 similar strings:
`E T9.onStartInput: inputType: 0 fieldId: -1 fieldName: null packageName: com.lge.fphome`
`E T9.onStartInput: inputType: 131073 fieldId: 2131492896 fieldName: null packageName: com.android.contacts`
com.lge.fphome is the launcher app. 
com.android.contacts is what takes over as the dialer once a number is inputed on the launcher.

**Comment by sspanak** [comment]
Got it, thanks! I'll see what I can do with this info.

**Comment by sspanak** [comment]
Here is the analysis info. 131073 = 0x20001, which means the input field incorrectly identifies itself as [multi-line](https://developer.android.com/reference/android/text/InputType#TYPE_TEXT_FLAG_MULTI_LINE) [text](https://developer.android.com/reference/android/text/InputType#TYPE_CLASS_TEXT) field. Naturally, this causes TT9 to start in text mode.

The `packageName` can not be used either, because this is actually the Contacts application. It has many fields of different types (when adding a new contact), so we can not simply force numeric mode for it.

The solution would be a device-specific hack (I guess I should create a `DeviceHacks` class in the end... :frowning_face:). The only way of detecting the dialer is by reading the Activity name. But normally, it is only available to the application that owns the Activity. [This Stackoverflow thread](https://stackoverflow.com/questions/44342214/getting-current-activity-name-in-service-class) is an example of getting the required info.

This would probably do the trick, but it will require extra permissions:
```
 ActivityManager am = (ActivityManager)context.getSystemService(Context.ACTIVITY_SERVICE);
    if(Build.VERSION.SDK_INT > 20)
    {
     String mPackageName = am.getRunningAppProcesses().get(0).processName;
    }
    else
    {
      String mpackageName = am.getRunningTasks(1).get(0).topActivity.getPackageName();
    }
```

I am stopping progress on this for now. I am not so keen on doing stuff for one specific device, especially when the bugs is in the device, given that there are many other tasks concerning/affecting all devices. Sorry, @DarthFlip, this will have to wait.

**Comment by DarthFlip** [comment]
Thank you for all of that info! Maybe I will try creating a fork with the edits required for my specific device. I agree that you should definetly be focusing on the tasks that involve all devices!
