### ISSUE TITLE
Suggestion bar shows over some apps without any input selected.

### ISSUE THREAD

**Issue by AF1512** [sspanak/tt9#218]
When I open Waze on my phone an empty bar shows over the app when it's not supposed to, see attached picture.
This also prevents clicking on anything under and below the bar.
On the TCL Flip 2
![Screenshot_20230317-144409](https://user-images.githubusercontent.com/67566814/225993174-c3bd8757-0251-41db-a5f1-17f5c94d8b95.png)

**Comment by sspanak** [comment]
I have received two more complaints, that are probably related:

- In Telegram, click on the stickers icon hides the keyboard for a moment, but then it opens again, hiding the stickers panel. Other keyboards stay hidden, until the icon is pressed again.
- In Snapchat, it is not possible to click the two buttons next to the "send a chat" field (I suppose they are "add an image" and "stickers" again). Supposingly, the TT9 window should be hidden, but it is not. This may or may not be caused by the same, but it looks very similar.

**Comment by sspanak** [comment]
I think I fixed the problem, but since I don't have Google, I can't test it properly.

If you want to give it a try, here is [an updated APK](https://github.com/sspanak/tt9/releases/download/testing/tt9-v19.8.apk). If not, I'll just include it in the next release. I believe it should be fine.

**Comment by joddsus** [comment]
Not fixed in snapchat in this version, still same issue with buttons in
bottom right corner in chats unresponsive when using tt9.

**Comment by sspanak** [comment]
@joddsus, the Snapchat problem is not related to this. I have created [a new issue](https://github.com/sspanak/tt9/issues/228). Let's continue the discussion and share any new findings there.

**Comment by lgexalter** [comment]
Can you let us know what you changed to fix that issue?

**Comment by sspanak** [comment]
@lgexalter, it is fixed and merged to `master` and it will become part of the upcoming version sometime next week.

**Comment by sspanak** [comment]
@lgexalter, [v20.0](https://github.com/sspanak/tt9/releases/tag/v20.0) is out. If the issue still persists in any application except Snapchat, reopen this issue. For Snapchat problems, check #228
