### ISSUE TITLE
"0" key not working for touch tones

### ISSUE THREAD

**Issue by lgexalter** [sspanak/tt9#225]
When dialing a number if zero is pressed it works fine, because it shows up on the screen, but no sound is made unlike the other numbers. This makes a difference when 0 is needed for touch tones. E.g. my voicemail password is 0000 and the voicemail does not recognize that anything was dialed when pressing 0.

N.b. I'm obviously kidding about my voicemail password 😝

**Comment by lgexalter** [comment]
@sspanak Was this fixed in the latest release? I saw you wrote something about fixing dialer field detection

**Comment by sspanak** [comment]
No, I haven't even reviewed this one. If it was fixed, I would have closed it.

The dialer field is the one where you type a phone number to call someone. I believe, it is not related to your case.

**Comment by DarthFlip** [comment]
I just came across this issue also. I was trying to order something over the phone and I couldnt key in the 0's in the credit card number. I had to hang up, switch ime, then recall.

**Comment by sspanak** [comment]
I've noticed some issues with 0 in Numeric mode, while I was working on #159. It is most likely another manifestation of the same problem.

@DarthFlip , @lgexalter , I need to know, when you face the issue, are you in Numeric mode? In other words, when you press the keys, do any letters appear or only digits?

**Comment by DarthFlip** [comment]
It was in Numeric mode and correctly displayed the "0" on the screen along with all the other numbers, however the automated system that I was on the phone with only recognized the other numbers. (On the screen it showed I had typed "12012" and the automated system said I had only typed in "1212").

**Comment by lgexalter** [comment]
Same as @DarthFlip

**Comment by mcfrei** [comment]
Could that be connected with the fact that all entries of 0 disappear for me on KYF33 in the calling interface as soon as I press any other key? like this:
*
*6
*60
*600
*6000
*6#

**Comment by sspanak** [comment]
@mcfrei, perhaps. I've definitely found problems with 123 mode and fixed them. It sounds like there may something else on your phone, but it may have the same root cause, as well. So, could you please try out the [latest beta release](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v20.1.apk) and let me know if the problem is resolved?

Also, pinging @lgexalter and @DarthFlip. 

Have in mind typing words may lag a bit in the beta, but I am going to optimize it in the final version.

**Comment by mcfrei** [comment]
@sspanak Thank you so much! 

The problems with disappearing 0 entries in the calling app are fixed in the latest beta release for me! 

However, there seems to be a slight other issue in the latest beta release for me, that the "Backspace" operation that deletes last symbol, does not abide to the configuration settings anymore - it is set to the key that is labeled as F3 in settings (keyCode 134 scanCode 62), but when the numbers are entered in the calling app, the "Back" key (keyCode 4 scanCode 355) produces "Backspace" operation instead, and the F3 key does nothing.

**Comment by sspanak** [comment]
@mcfrei, if it is only the calling app, this is intentional and it is like this since the beginning. Calling (dialer) apps handle the keypad on their own. I am not aware of any way of changing this. If Backspace does not work properly in all apps, please create a new issue. This one is about 0-key.

**Comment by lgexalter** [comment]
@sspanak Seems to be fixed. Thank you!

**Comment by mcfrei** [comment]
I was able to build a debug version and check it on the phone.

The problem I mentioned earlier, with disappearing 0 key, is still present in the latest master commit I have (7f6cd61) marked with 20.0 tag.

However this problem is absent in the latest beta release you shared earlier, and in the build from the branch soft-keyboard-numpad (221cc21).

By running the adb logs on the app from the 20.0 version I was able to see excessive spam on every button press in logcat whenever I try entering digits in the calling program interface, and these logs are absent from the branch (221cc21) version:

W/IInputConnectionWrapper( 4003): setComposingText on inactive InputConnection
W/IInputConnectionWrapper( 4003): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4003): setComposingText on inactive InputConnection

And the following log is present on button press in calling interface in any version (both branch (221cc21) and 20.0 (7f6cd611))

E/SpannableStringBuilder( 4003): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

The last string about zero length spans is also present in [123] mode on other input fields, not only in the calling interface.

I am currently searching for a way to enable debug logs in the keyboard app to have more information on the issues. I have tried to filter adb logs with the app id io.github.sspanak.tt9 by using the command

 adb logcat *:S io.github.sspanak.tt9:V

 but there was nothing in the filter, so the search continues. I would really like to present detailed debug logs for the io.github.sspanak.tt9 on the following issue which seems to be the same. 

Also, let me know if I should open a separate issue with this problem, I wrote comments because I don't want to issue spam if it can be avoided.

Also, let me know if you want a video recording of the bug behavior together with adb logcat, I think I can manage that.

Steps to reproduce the current issue is as follows:
Install the keyboard app, all settings by default.
Press [1] on the main phone screen, opens the calling interface with the digit 1 typed.
[2]: 12
[3]: 123
[*]: 123*
[1]: 123*11 (note that the every key after the star is entered twice)
[2]: 123*1122
[3]: 123*112233
Press [📞/Power] button to close the calling interface and return to the main phone screen, the steps now can be repeated. Not only [*] button does the duplication of the entered keys, but also [Back button] (key 4 scancode 355) deletes one digit but leads to the following digits double input.

However this behavior is much more erratic in the branch version (221cc21) and I really want to diagnose the issue with doubling keys myself, so please kindly let me know how to collect and view debug logs and I will review the code in the branch (221cc21) version to diagnose the issue.

**Comment by sspanak** [comment]
@mcfrei, please create a new issues for the Backspace problem. Also, you may want to wait for #242 and #243, where I have fixed many small bugs.
