### ISSUE TITLE
Hotkeys, Cannot Input * or # in 123 Mode

### ISSUE THREAD

**Issue by alexknop** [sspanak/tt9#246]
Phone: Cat S22 Flip
First noticed when trying to dial # in the phone app that * and # are not working when 1-0 worked.
Then went to the messaging app and changed my mode to [123] and had the same issue.
The problem is occurring because these are hotkeys.
In the instance I open my phone dialer, the typical black row that shows on my screen for tt9 is hidden. It seems that the phone has called the [123] dialer by default. In the event it is called like this (different from when it opens for messaging) would it be possible to disable hotkey functions?
As a semi-workaround, I have changed my # press hotkey to be disabled. I use# hold instead for my  change keyboard function, and have dropped function to change language. However, someone facing this may desire to have those functions.
It is not possible to do "add word" as * hold. Perhaps that can be added.
It's also not possible to null out the "open settings" hotkey. Perhaps that can be added too.

**Comment by sspanak** [comment]
I see what you mean. I agree the hotkeys must remain disabled in some "special" input fields, when the suggestion/status bar is hidden.

In regular text fields, when you have manually selected 123 mode, I guess, the Language and the Add Word keys could remain off (I am actually already working on this), but I am not sure about the rest. If you have chosen "#" to work as Backspace or "Open Settings", it has to keep working like this, because... well... you chose that.

> It's also not possible to null out the "open settings" hotkey. Perhaps that can be added too.

Right! This is intentional. In the beginning there was no other way of accessing the Settings, so I wanted to ensure the users couldn't cut the access accidentally. But now there is a launcher icon, so this is no longer necessary. I'll make it nullable.

> It is not possible to do "add word" as * hold.

It is possible. Perhaps you had "* hold" assigned to something else when you tried?

**Comment by sspanak** [comment]
Status update:

Problem 1 ought to be resolved in v21.0.

Problems 2 and 3 ("not possible to do "add word" as * hold", "not possible to null out the "open settings" hotkey"), do remain, but they are planned for version 22.
