### ISSUE TITLE
double press comma

### ISSUE THREAD

**Issue by joncede** [sspanak/tt9#273]
Hey there!

would it be possible to implement a customizable Double Press 0 input? I would love to put a comma there intead of a dot or space!
I'm sorry if this is already implemented but I couldn't find it in my usage 😅

Love this app, you are doing god's work!

**Comment by sspanak** [comment]
Hey!

"," is easily accessible even now. You can type it by pressing 1-key once. I know that currently, there are some issues with English, Dutch and Hebrew - the punctuation marks would appear joined with the word or some of them will be missing in sometimes, but all this will be fixed in #187.

Meanwhile, I could consider adding "," to the double press list. It is an easy one.
