### ISSUE TITLE
Portuguese Dictionary (Pt)

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#317]
Hello!

Amazing keyboard!!! Working great already!!!

I'm just starting to test the on-screen numpad and already pretty happy with it!

However i would like to ask if you can add the **Portuguese** dictionary (from Portugal, not the already-added Brasilian one)

thank you

**Comment by sspanak** [comment]
It is doable, yes. Have in mind, though, I'll be busy with fixing bugs and cleaning up the code for a while, so I don't see it happening in the next release or even the one after.

**Comment by maverick74** [comment]
@sspanak OK. I'm just testing the app for the time being also... So **pt-br** will do the job until **pt** comes along.

Word prediction works amazingly well, BTW!!! **You've done a truly amazing job!!!** I'm really **really** surprised about it!!! **Congratulations**!!!

I'm a bit puzzled why i can't access it from NewPipe, however... should i fill a bug report about it?

**Comment by sspanak** [comment]
> I'm a bit puzzled why i can't access it from NewPipe, however... should i fill a bug report about it?

Yes, if there is a problem, let's discuss it in a separate issue.

**Comment by maverick74** [comment]
Question: do you already know or have an idea 
where to get the pt dictionary, or can I try to help by finding one?

(I'm not trying to speed things up! Just trying to be of some help...)

**Comment by sspanak** [comment]
Usually, for Latin-based languages I just use the Android OSP dictionaries and convert them to the appropriate format. They are OK, but since they are meant to be used with a QWERTY keyboard, many words are missing and using them in TT9, you can feel they are incomplete.

I suppose there is some Portuguese institute or academy that regulates the language. If they have "a list of all words" or something similarly named, we can use it to improve the typing experience. And since it is very difficult to me to search for resources in a language I don't speak, if you can find a dictionary in the Portuguese part of the web, it would be great.

**Comment by maverick74** [comment]
OK... sooooooo... i've been trying to find the latest official "open" dictionary that can be used (GPL licensed)... here's what i found:

There are a few colaborations with libreoffice about this and that they make the dictionaries available in their page: [LibreOffice Dictionaries](https://pt.libreoffice.org/descarregar/dicionarios/)

However, in fact, they are just using the dictionaries made available thru a project led by _[Universidade do Minho](https://www.uminho.pt)_ (which is a respected university around here): 

[**Project Natura**](https://natura.di.uminho.pt/wiki/doku.php?id=dicionarios:main) **<- download links available here**

The project makes available two major dictionaries: the **pré-AO** and the **pós-AO**. Here's what this means:

There have been a series of **Orthographic Agreements** (Acordo Ortográfico, AO) between all the Portuguese speaking countries over the years.
The intention is to make all Portuguese Language countries write and talk more or less "the same".
For that end there is the Post-Orthographic Agreement (_Pós-Acordo Ortográfico_ in portuguese, or **_pós-AO_**, for short)

However, this has had limited  application (even if that's the recommend by law in Portugal) and has seen some resistance!

As such there is the Pre-Orthographic Agreement - which is the way we always used to write - the official way before 1990... and still the way most people write (_Pré-Acordo Ortográfico_ in portuguese, or **_pré-AO_**, for short).

So, it will be up to you to choose which version you'll use.
Note: the **pré-AO** is not illegal and is still in use ... "_officially_"... 
also considering the target-people of TT9 i believe this would be the best option! (that's how we wrote in Nokia ahaha)

however, on the other hand, **pós-AO** will probably not be revised and will probably be the way forward... (just... maybe not now... ;)

I think we could also use the pré-AO for starting and if you get any bad feedback (which **i don't believe you will**), eventually migrate to pós-AO... Then again... it's up to you :)

Hope i helped :)

**Comment by maverick74** [comment]
Out of curiosity... in the dictionary files (the csv files, I presume) what are the numbers???

**Comment by sspanak** [comment]
> OK... sooooooo... i've been trying to find the latest official "open" dictionary that can be used (GPL licensed)... here's what i found...

Thank you very much for your efforts. I'll review everything, as soon as I have free time.

> also considering the target-people of TT9 i believe this would be the best option! (that's how we wrote in Nokia ahaha)

Who are they, actually? :slightly_smiling_face: If you are indeed born in 1974, I am almost 15 years younger and I still prefer T9 over QWERTY when using a phone. I even use TT9 on my touchscreen-only smartphone, because I am more comfortable typing this way. And there will be more and more younger people in the future, I am sure.

Anyway, from what I understand, the "old way" of spelling is the preferred one. Still, I'll do my own short research to confirm and make the final decision.

> Out of curiosity... in the dictionary files (the csv files, I presume) what are the numbers???

They are the word frequencies - the key to good predictions (well not the only one, but it is very important). [Here](https://github.com/sspanak/tt9/blob/master/CONTRIBUTING.md#dictionary-formats) is a description of the supported dictionary formats. But don't worry about these. Databases with the most popular words are freely available from Google, so I can get them easily.

**Comment by sspanak** [comment]
> All in all: yeah you should indeed do your own short and independent research as my view may not express the actual reality.

Alright, will do.

> About word frequencies... my intention was to help in anyway i could, but if you prefer doing it yourself that's even better has i'm short of free time and not that much experience :)

This is literally a five minute job. Don't worry about it at all.

**Comment by maverick74** [comment]
Ok...
I've tried not to ask you this but since its a quick job I have to:

can you please add this before I jump with both feet over my phone?

I quit!!! I though I could but I was wrong: I cant keep using a brasilian dictionary!!! There are lots of differences!!! Lots of words missing!!! I have added dozens of words by now (a lot more than in all my years using touchpal) and I keep on adding!!!

Even using words that are closely related and that are not used in the rest of the Portuguese language countries - I keep on adding!!!

Its crazy!

So, if I'm not asking too much, could you - please - consider adding a decent Portuguese dictionary (when you got the time)?

Thank you so much!!!

**Comment by maverick74** [comment]
Ok, it's not worth the work just to test it... forget it then... i'll wait for a release from you.

I was hopping to test it before submitting it just to have a notion about the _quantity_ of words (if it lacks anything, like the pt-br dictionary)

I used the dictionaries from the links i sent you above. I was aiming at the **pós-AO** for being more "future proof" but it seems to have a lot less words that the **pré-AO** (about 31.000 words less to give you a clue), so i ended up choosing the **pré-AO** (with 32.938 words).

I did nothing special, i just edited the xml in _kde kate_ and removed "everything" but the words and saved it in .txt.

Is that even worth sharing? :)

**Comment by sspanak** [comment]
> I was hopping to test it before submitting it just to have a notion about the quantity of words (if it lacks anything, like the pt-br dictionary)

No need to test, I can answer directly: ~30k words or not enough at all. Even a simple language like English has a dictionary of 130k (by simple I mean, the words do not change much - by gender or number, verbs have only 3-4 conjugations in total, etc...). Yet, a lot is missing. In the past couple of weeks I have searched for and added 40k new words and now I hope it will feel more complete.

Based on my experience so far, I assume the Portuguese dictionary would have to contain around 300k words for regular everyday conversations, but you would still be missing words, when typing on specific topics. A list of 1 million would feel complete, I believe.

**Comment by maverick74** [comment]
OK... a million is a lot! I was not expecting that much!!!

I'm not searching the right places for sure, then!

Does the "place" where you usually get languages from also has Pt in it?

**Comment by maverick74** [comment]
> OK... a million is a lot! I was not expecting that much!!!
> 
> I'm not searching the right places for sure, then!
> 
> Does the "place" where you usually get languages from also has Pt in it ( Android OSP dictionaries if i'm not mistaken)?

**Comment by sspanak** [comment]
"The place" is Android itself. :smile: 

I've just checked - as usual it has a small dictionary which is fine for QWERTY, but a bit insufficient for T9. It contains a little more than 200k words. I guess it is a good start, but I'll search for more.

Meanwhile, if you come across a complete list, which contains all word forms, please share it. There may be some Portuguese website that hosts such list.

**Comment by sspanak** [comment]
@maverick74, I've checked the Projecto Natura website and found a potentially useful word list. The things is, it contains expressions that need to be separated into words. For example:
```
trazer-nos
trazer-nos-eis
trazer-nos-emos
trazer-nos-ia
trazer-nos-iam
trazer-nos-ias
trazer-nos-á
trazer-nos-ás
trazer-nos-ão
trazer-nos-íamos
```

These, in particular, may not be commonly used, but how common is for Portuguese people to express themselves this way? When you write something, how often do you join words and pronouns with hyphens like this ("xxx-nos", "xxxx-íamos", "xxx-iam", etc).

I am asking this, because I want to know whether it is better to separate them completely, or leave the shortcuts with hyphens for faster typing. So, if the original word is "trazer-nos-íamos", shall I keep only "trazer", "nos", "íamos" or also add "-nos" and "-íamos". 

If I keep them it would be possible to type "-íamos" by directly pressing "142667", and if it is only "íamos" you would have to: press "1", select the hyphen, "OK", type "42667". These "shortcut words" are only useful when used very commonly, like English "I'm", "It's", but if you use them rarely, it won't matter much. And it will make my job somewhat easier. :slightly_smiling_face: 

It feels like the better option is to leave the hyphen-prefixed variants, but I have no knowledge of Portuguese, so I would like to hear a native speaker's opinion, too.

**Comment by maverick74** [comment]
> These, in particular, may not be commonly used, but how common is for Portuguese people to express themselves this way? 

We use hyphens with some frequency!!! It's an "_usual_" thing.

For example, i went to a news' site and picked up the first post i found (randomly):

https://24.sapo.pt/atualidade/artigos/agricultores-polacos-intensificam-protestos-com-grande-mobilizacao-nas-cidades-e-fronteiras-com-a-ucrania

if you make a quick search for words with "-" you'll find nine in this article...

so... it's a common thing, i would say.

> It feels like the better option is to leave the hyphen-prefixed variants, but I have no knowledge of Portuguese, so I would like to hear a native speaker's opinion, too.

yeah, i agree that the better option to use them!

**Comment by maverick74** [comment]
> These "shortcut words" are only useful when used very commonly, like English "I'm", "It's", but if you use them rarely, it won't matter much. And it will make my job somewhat easier. 🙂

Still... _while keeping them to make it possible to type "-íamos" by directly pressing "142667"_ would be the ideal,

if it means it will considerably delay the deploy of the dictionary, i would prefer to "manually" type the hyphen...

**Comment by sspanak** [comment]
Understood, let's keep them. I won't take _a lot more_ time. I've done six languages in January, so...

**Comment by sspanak** [comment]
@maverick74, I think I am done with Portuguese. The final result is 643000 words, which is not bad at all. Likely, from time to time, you'll find some words are missing, but the overall experience should be quite OK. Also, there are some incorrectly capitalized words and some in lowercase that must start with a capital letter. I've tried to fix as much as I can, but I have probably missed some. Feel free to report.

It is also worth mentioning that I've read about the spelling reform and I figured it's better to go with the post-1990 word list. If this is the current standard, let's stick to it.

Here is [an updated APK](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v27.36.apk) for you to test. Have in mind, this is not the final release. It's mostly stable, but there may be bugs here and there. Most notably, you may notice that in messaging apps, when you send a message, right before you start typing a new one, the last word from the previous one may re-appear.

There is also a small chance that the upgrade from v27.0 could fail completely, preventing TT9 from starting at all. If this happens, just uninstall and reinstall. I think I have fixed it yesterday, but I haven't yet tested it thoroughly.

**Comment by sspanak** [comment]
> 643K... where did you got that many?!?! Did i download the wrong file or something?!?!

Well, I've combined 3 lists, but most of the words are from Projecto Natura. The XMLs on top, that you've tried to use contain only the words from the last update, while the complete lists are at the bottom of the page.

The Android words turned out to contain a lot of garbage and generated nonsense, such as:
```
AAA
AAAA
AAAB
AAAC
BBBB
BBCC
etc ...
```
They were so bad, I decided to use only a few acronyms and international words that you may also use in Portuguese, such as: "DJ", "OK", "kg", "km" and so on.

> Upgrading from 27.0 went ok. No problems.
I'm going to try it on my everyday use and i'll report anything i find.

Yep, let's give it a few more days and if there are no critical problems, v28.0 should be good to go. We can do additional small improvements in the future.
