### ISSUE TITLE
Dictionary not available in NewPipe

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#319]
When using NewPipe and i try to perform a search, the selected dictionary is not available.

![newpipe](https://github.com/sspanak/tt9/assets/14912461/9a58f623-66a9-4302-aae1-c57f6a5035ec)

I don't know if this is specific of newpipe or if it happens in other apps. NewPipe is the only app i found this problem so far

**Comment by sspanak** [comment]
This is something with NewPipe. I suppose the search field is of type "TYPE_TEXT_VARIATION_FILTER" or some unrecognized type, so TT9 just allows "simple" typing, but I am not 100% sure. I'll investigate further, when I have time.

**Comment by maverick74** [comment]
@sspanak regarding this: if i can help in anyway, let me know about it!

**Comment by sspanak** [comment]
Oh, my previous comment is just a note to myself, so that I don't forget what to look for.

> if i can help in anyway, let me know about it!

If you have programming skills, you could check `TextField.determineInputModes()` and find what's the reason for it not to include `MODE_PREDICTIVE` in returned list. If not, you just have to wait. I don't have so much free time to work on TT9 lately. Sorry!

**Comment by maverick74** [comment]
> If not, you just have to wait.

That's what I'll do then! I have no skills in Android codding (I had some Java on university, but nothing that helpful! I'm more comfortable on C++ and Sinclair BASIC ahahah... and even on those I'm not an expert either 🤣 )! Sorry!
