### ISSUE TITLE
Some Requests

### ISSUE THREAD

**Issue by theancientways** [sspanak/tt9#329]
This is a great piece of software thank you for all your great work. These suggestions are for the dumbphone users; my device is the Kyocera DuraXV Extreme+. The goal of all these suggestions is to give the user the option of moving almost all functions to the keypad, which will increase typing speed by eliminating the action of having to reach up to the navigation pad.

1) give us the option to change the spacebar to the # key or the asterisk key. If you type space with your right thumb, the # key is a tad closer to where you thumb is. (Vice versa for left handed typers and the asterisk key).  

2) give us the option to change the “next suggestion key” to the 0 key. Again eliminating the action of reaching up to the navigation pad.

3) when cycling through word predictions, let pressing the “clear” button reset the word back to the word you originally typed. Next press of clear button will activate backspace.

4) let us modify the order of symbols attached to the “1” key. For example, if you assign ? as the 2nd suggestion, you can press 1, 0 to quickly type a ?. Also, people may want certain symbols to be closer based on which ones they use more often.

5) Allow the shift action to be assigned to either the asterisk or # key. 

6) give us the option to change the next input method button to the left soft key (ideally let this bring up a little menu where you can select the different input options). Since this is usually a less used function get it out of the way to allow the Asterisk, 0, and # buttons to be assigned to more frequently used actions.

7) integrate the “add word to dictionary” function as an option in the change input menu that would appear when pressing the left soft key as requested above. Again clearing up the lowest row of the keypad for more frequently used actions. 

8) The next prediction option after “its” should be “it’s”. Same with any other word that has a common variant with an apostrophe like your and you’re.

9) I noticed that there is no / or \ in the symbol options, it would be great to have these as well. 

I know I'm throwing a lot at you here, I feel like I may have been able to condense/combine these, sorry if it's a little lengthy. I guess in summary I'm just requesting to give the option to move more actions to the lower row of the keypad to allow for faster typing. Thanks again!

**Comment by sspanak** [comment]
1 and 2. Sorry, this is not going to happen. All the code is built around the idea that number keys are used for typing and all others are used for invoking keyboard functions. Changing this is a significant effort and is not worth it from my perspective. Also, the aim is to bring Nokia experience to Android. This _is_ the Nokia way.
3. You originally typed all the words you see. Which one is the original one? If you typed "4663", how is the keyboard going to decide whether you wanted to type "home", "good", "gone", "hood" or something else? I don't think there is an easy answer to that. :slightly_smiling_face:
4. This used to be possible at the beginning, but caused technical problems, so the punctuation list is now fixed. As for the question mark, it is the second option. Press 1-key, then go back one time and you'll select it. It is possible to scroll past the edge of the screen. Both the punctuation and the special character suggestions are ordered to allow at least some convenience. I have thought about this.
5. This is possible even now. Go to Settings -> Keypad -> Select Hotkeys and adjust all functions to your liking.
6. This will happen in #301. Follow that issue for more info.
7. In #263, all functions/commands will be grouped under a single command palette both for convenience and to allow for new ones in the future. It will be possible to invoke them with key combos, for example #+1 to show settings or #+2 to add a word. The "command" key will be configurable. I realize there is no more room for new stuff and improvement is necessary.
8. The dictionary used to contain words like "it's" or "you're", but over time, this proved to be very limiting. Not to mention it increased the dictionary size significantly, because all words had to contain their possessive versions. The problem was even bigger with French or Italian, where they have many more contractions. Currently, "'s" and "'re" are separate "words", so you could combine them with any other word. Initially, it may look weird, but it is in fact more efficient.
9. Press 0-key to type them. 0-key holds the Math and Special characters list, while 1-key is for the characters normally used for typing text.

All in all, there are separate issues for some of the things you have suggested, some others are possible even now and the rest, I will have to reject them. Sorry, if it feels disappointing, but so many people are asking for something, sometimes the requests even contradict each other. And sometimes, they are impossible or very difficult from techincal perspective. I cannot fulfil all of them.

**Comment by theancientways** [comment]
Hey thanks for such a thorough response. The requests I gave were all based off of the "T9 Word" input method from the LG Exalt LTE. I can type on that phone just as fast as I can on a computer keyboard. It’s simply the best T9 text input layout I’ve ever come across and it’s because all the typing happens on the number pad. You only have to jump to the soft keys/directional pad if you need to switch typing inputs or type advanced symbols. If you could extract the LG Exalt LTE’s T9 system and make it available as an APK I’d literally pay you, I think it’s that good. 

It makes sense that if you’re modeling this APK off of Nokia’s text input software that you’d want to stick to that layout, so I understand that.

**Comment by theancientways** [comment]
patiently awaiting v25.0, you're awesome, thanks for your work!

**Comment by theancientways** [comment]
> EDIT: I see what you mean. There is a bug in v24.0 that prevents from assigning any key to "next suggestion", but the fix is on the way. Stay tuned for v25.0.

Hey, was this actually implemented? I'm on v26 and I see no way to assign any key to "next suggestion", it's still limited. I'm on a sonim xp3plus.

**Comment by sspanak** [comment]
> Hey, was this actually implemented? I'm on v26 and I see no way to assign any key to "next suggestion", it's still limited. I'm on a sonim xp3plus.

It most certainly is. Go to Settings -> Keypad -> Select Hotkeys and look for "Previous Suggestion" and "Next Suggestion"

**Comment by theancientways** [comment]
Genius – thank you for the explanation! You were right, other keys weren't showing up because they were assigned to other functions. I now assigned "next suggestion" to the # key and it makes typing a little speedier. Thanks again for implementing this!

**Comment by theancientways** [comment]
No chance you can also allow for changing the key assignment of the spacebar function?

**Comment by sspanak** [comment]
No, sorry, I have no such plans.

**Comment by theancientways** [comment]
no problem at all, I was just trying to be able to duplicate the way the LG Exalt LTE's typing functions were laid out, as that's the device I was using for years prior. This however is very minor change and I am already adapting to having the spacebar as the 0 key and switch to next word as the # key. Overall I think you did a great job and this is an excellent piece of software, miles better than the trash native text input methods of the Sonim XP3plus and the DuraXV Extreme+. It makes these phones usable for texting. I will be donating to you to show my support and appreciation.

**Comment by sspanak** [comment]
Oh well, TT9 has pros and cons and using it you get both. It will be the perfect keyboard, but it can be a nice choice. Thanks for making that choice!
