### ISSUE TITLE
Some English words have incorrect text case

### ISSUE THREAD

**Issue by alexknop** [sspanak/tt9#339]
Hello,

It seems that the words "news", "wonder", and "case" are all in the English dictionary as 
NeWS
Wonder
Case

It seems they are all considered references (to a last name, pop culture reference, etc) but I find it odd since they also should be regular English words and in lowercase. Whatever the source is for this dictionary, I wonder if a function was ran that removed duplicate words (removing news since NeWS was available) and that is why it is like this way.

**Comment by sspanak** [comment]
> Whatever the source is for this dictionary, I wonder if a function was ran that removed duplicate words (removing news since NeWS was available) and that is why it is like this way.

Exactly, in the last release I merged two word lists and ran a script to remove the repeating ones. I've already noticed "NeWS", but I didn't know about the others. If you come across any others, please list them here, so I can correct them in the next release.

Thanks for reporting!

**Comment by sspanak** [comment]
Adding to the list:
- cia
- fbi
- mr
- mrs
- tnt
- vcr
- vip
- dos
- aalborg
- aalesund

**Comment by alexknop** [comment]
I don't think removing the duplicates is good for the end-user. I think users should be given both options because as of now a user has to change the case of the suggested word. 
Sure, it probably saves space, but sometimes a user wants to type "states" and not "States" (probably a reference to United States). It's extra effort to change the case instead of having it as a default option.

**Comment by alexknop** [comment]
Also, I think it would be helpful for people to have these words in the dictionary by default:

- haha
- lol
- lmao

**Comment by sspanak** [comment]
Fixed in #407.

**Comment by alexknop** [comment]
I have found a couple of anomalies from this, i.e. "CARE" . I imagine there was a conflict with the lowercase word and a word for a popular company, etc. and the all-lowercase was removed?

**Comment by sspanak** [comment]
Yeah, it is difficult to mass-process thousands of words without making a mistake. Thank you very much for pointing this out. Please, list any order incorrect words that you have noticed and I'll correct them too.

**Comment by alexknop** [comment]
"news" is spelled "News"

**Comment by sspanak** [comment]
I simply can't get this word right... :laughing:

It will be fixed in #424

**Comment by alexknop** [comment]
"target" only has the dictionary entry with a capital referring to the store called Target

**Comment by alexknop** [comment]
"Numbers" as well

**Comment by sspanak** [comment]
Forgot to reply back, but they are both fixed in v27.0. Please, keep reporting or even consider opening a PR where you directly fix the words. We can keep collecting them until the next release.

**Comment by sspanak** [comment]
"Burger" is fixed in the v28.0 branch and will soon be in `master`.

So why not have multiple versions of each word? There are a couple of problems with this.

First, it's usability. If the dictionary contains both "Burger" and "burger", it would be possible to tell which one is which only in the middle of a sentence, and if no text case is forced. However, if this is the first word in the sentence, there would be two "Burger" suggestions. Or if the user has selected upper- or lowercase manually, they would see "BURGER" or "burger" twice. 

Moreover, they may not appear one after another. For example "bushes" may appear between them, because it could have a higher frequency than one of the burgers. This could be confusing. 

Second, even if one of them starts with a capital "B", one may ask why are there so many burgers. They would be taking too much space, when one may be looking for another word. This will escalate, if there are many duplicate words.

Third, this is data duplication, which is bad for performance. You may think it is not a big deal, because there would be only two burgers, but let's look at another example. In most Slavic languages there are cities that include the word "new" in the name, like "New York" or "New Orleans" in English. But "new" has 1 form in English, while in Bulgarian it has 8, and in Ukrainian it has at least 28. I am not sure if there are more in Ukrainian, but they definitely have 7 cases * 3 genders, singular + 7 cases * plural. This means that it may be one extra word in English, but 8 extra words in Bulgarian and 28 extra words in Ukrainian. So, you see, it will quickly scale up, as there would be many such words.

And in order to "compress" the required space, I prefer having only one version of each word and let the user to change the text case in a key press. If there were two "burgers" or two "news", again, one would have to press a key to select the next suggestion, in order to change the text case. So, it doesn't matter anyway. From number of actions perspective, there is no difference.

And one more thing, considering the increased storage space. I don't think it is possible to optimize the search speed much more, after what I did in v27.0. Currently, I am certain TT9 runs smoothly with up to 1.5 million words. Probably, it will be fine even with 2 million. But duplicating the words, just to have capitalized suggestions will push the upper boundary a lot. I don't want to go there.

Hopefully, this answers your question.
