### ISSUE TITLE
Schok Classic Virtual Mouse Issue

### ISSUE THREAD

**Issue by pexxdev** [sspanak/tt9#350]
Hi there! Wanna start off by saying thank you for creating such a solid IME for hardware keypads!! And for maintaining it so beautifully! I love my flip phone but it is hard when they're designed rather poorly out of the box (I feel like they all have their quirks) and not many people build apps for better functionality. So it was lovely to run into this one :) I have a Schok Classic (SC3218) running software version SC3218_V1.1.9 and unfortunately, I'm unable to really use TT9 right now because it also completely disables use of the Schok Classic virtual mouse. The mouse is what gives me a signiiiificantly smoother experience with running apps that are meant for touch screen, like my primary messaging app, so I don't really have a choice on which to keep. I can have the app installed but as soon as I set it as my default keyboard, that virtual cursor immediately stops working. It will appear on the screen when I short-press the multi-function button on the phone (that's not default, I have the keys mapped that way, but it is a stock feature on the phone to be able to do that) but then if I try to use the D-pad to move the cursor, it stays still. At first I thought that maybe the issue was because I had the D-pad mapped to stuff on the keyboard and was trying to use them to navigate the cursor but when I turn off the virtual mouse, the D-pad works just fine for other things so not sure what's going on.

**Comment by sspanak** [comment]
Thanks! I'm glad you like TT9.

Now, to your problem. I assume you have installed the current latest v24.0. Unfotunately, it mishandles the D-pad and even if you unassign all keys, they still don't work in all applications. A fix for this bug is already on the way, However I am not 100% sure it will fix your problem. It sounds like this is yet another highly customized non-standard Android version that may be designed around Schok's own keyboard. If that is the case, it may be very difficult for me to diagnose the problem, without having the device in my hands.

Anyway, let's wait until v25.0 comes out and see if it fixes the problem.

**Comment by pexxdev** [comment]
Sounds good, I'll keep an out for the release and see how it goes! I'm also going to be doing some experimenting and research into how some of the features on the phone work in an attempt to build my own custom launcher for it so if I find any information on how the virtual mouse works that might be useful to you in figuring out how it's interacting with TT9, I'll put it on here.

Again, appreciate the work you're putting into this and the quick response!

**Comment by sspanak** [comment]
[v25.0](https://github.com/sspanak/tt9/releases/tag/v25.0) is out. Please, go ahead and check if it fixes your problem.

And of course, feel free to examine the code and build tools better compatible with your phone.

**Comment by pexxdev** [comment]
IT WOOOOOOOORKS!!!! :D Thank you so much!!! It's soooooo much easier to type stuff now :)

**Comment by sspanak** [comment]
Excellent! It's great to hear it. :slightly_smiling_face:
