### ISSUE TITLE
keyboard does not open in termux

### ISSUE THREAD

**Issue by evantj** [sspanak/tt9#353]
termux does not cause this keyboard to show. this issue does not reproduce in any other app, nor with any other keyboard. i know that termux does some strange things with the android soft keyboard to make it work the the terminals io scheme, so presumably something about that doesn't work with this keyboard. i have no idea if this is a termux issue or a tt9 issue, but i had to ask somewhere first.

**Comment by stianhoiland** [comment]
Ooh, imagine adding terminal commands (and completions?!) to the dictionary. A poor version of something I've thought a little about in other contexts: Having a way for the app to contribute predictions to the keyboard. (For example a terminal app contributing commands and tab completions.)

**Comment by sspanak** [comment]
> termux does not cause this keyboard to show. 
I haven't used termux before, so I don't have a quick answer why TT9 isn't working. The list of requests is getting longer and longer every day, so I can't promise I'll get to this bug soon, but I'll eventually do so.

> Ooh, imagine adding terminal commands to the dictionary.
That's not a problem at all. You could add a new language and call it "Bash" or "Zsh" or "Windows CMD" or whatnot, and put a list of commands and parameters. You'll automatically get autocompletion. :slightly_smiling_face:

**Comment by sspanak** [comment]
I've managed to get it working, but Predictive mode is not going to work. Termux does not support text retrieval or editing, which are crucial for Predictive mode. Nor does it support displaying suggestions, so even the ABC looks a bit weird, because the current candidate is not visible in the terminal until it accepted. But that's the best I can do.

@evantj, if you have time, please try [v25.8](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v25.8.apk) and let me know if it works fine for you.

**Comment by evantj** [comment]
it works, thanks so much!
