### ISSUE TITLE
TT9 independent clipboard

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#360]
So now, afaict, tt9 is using android's clipboard.

My suggestion is for it to use it's own clipboard for security and privacy reasons.

Case: imagine i need to copy/paste some password. I would prefer to trust TT9's clipboard than android's.

Still, this poses a question that may completely invalidate this issue:

**Will a TT9 clipboard still be using android's clipboard on the background?**

- If so, then it invalidates the issue and you can safely close it.
- If not, then it would be a good addition (if it is an easy thing to do and does not bloat the app...)!

**Comment by sspanak** [comment]
First, at the moment, TT9 has no support for copying and pasting. In other words, it is not using the clipboard at all. What you can do now is entirely function of your phone. 

Text operations will be introduced in #170 at some point in the future, but I have no plans in creating a custom clipboard. Here is my reasoning:
1. It will not increase security at all, because everything you input goes through some system function or API before getting into the target application. If "they" want to know what you type, you can not hide it this way.
2. I don't really believe in that whole "they are watching" conspiracy. "They" don't care about you. And this is not how passwords get stolen. Either people use very easy-to-guess passwords, or some employee at a big company sells database dumps to "them".

So, the short answer is: no, I will not implement a custom clipboard, because it is of zero value.
