### ISSUE TITLE
Long press on the buttons, assigned as the system volume up/down hotkeys on Qin F21pro, changes the volume but doesn't perform the expected keyboard function.

### ISSUE THREAD

**Issue by qascot** [sspanak/tt9#369]
There are no special buttons for changing volume on Qin F21pro. Usually, the numbers 8 and 0 are used as the volume up/down buttons (could be selected in System > Quick Settings). Until the Volume Up and the Volume Down hotkeys  appeared in TT9 settings everything worked fine. Now a long press on the system volume hotkey leads to a volume change, but not to the expected TT9 keyboard function (entering a number in prediction mode or selecting a character in 123 mode). Changing volume system hotkeys leads only to incorrect functioning of another numeric keys. The only way to use the TT9 keyboard without problems is to disable the system volume control hotkeys, but using this phone without the system volume control hotkeys is inconvenient. Could you do something about it?

**Comment by sspanak** [comment]
At the very beginning the volume keys used to work properly, but they have stopped after a firmware update. Since I have other system hotkeys set, and they don't interfere with TT9, I assumed it is not possible to use the volume keys for anything else, so I haven't investigated the problem.

I doubt it is possible to fix the problem, but let's keep the issue open. I could try to tackle it in the future. Any help is welcome too!

**Comment by qascot** [comment]
TT9 v17 still works properly on the system firmware updated to version 1.1.6. Probably, this can help to find the bug.

**Comment by qascot** [comment]
I've tested some older releases and found that this issue appears in v.20. Up to v.19 there were no problems with the volume buttons.

**Comment by sspanak** [comment]
I've reviewed again the changes between v19.0 and v20.0 and I've found the culprit. I must say, this bug is a perfect example how messed up Android is on some phones. 

On this phone, the "Shortcut Keys" app checks whether there is a keyboard status icon, in order to disable itself, when any keyboard is active. And in version 20.0, I've removed the icon, which caused "Shortcut Keys" to always take precedence, because it was no longer able to detect TT9 was active.

I'll just create another hack for this under Initial Settings -> Compatibility... :cry:
