### ISSUE TITLE
Can't make "i" default letter for "4" key

### ISSUE THREAD

**Issue by henry02843** [sspanak/tt9#397]
On cat s22 flip, I am unable to set the default single letter to "i" when pressing the 4 key. Every other letter on the keyboard is able to be assigned as the default by holding the center/select button on the suggestion. When doing this with 4, G and H can be made the default letter, just not i.

**Comment by koalabuttz** [comment]
I can confirm I have this issue on the same phone as well.

**Comment by sspanak** [comment]
TT9 ignores holding the central button, it just passes it through to the current app. You can not use it for making any word the default one.

To do so, just type normally. Both the central key and 0-key (space key), will change the word priority, but don't hold them, use single press.

And if there is a problem with the dictionary, I believe it will be fixed in #366, meaning - in the next release. If you still have problems even in version 27 (when it comes out), please report again. Otherwise, I'll consider the bug fixed after the release.

**Comment by Subspiria** [comment]
I had this problem, where pressing 4 would return "g" when in predictive mode. What fixed it for me is adding "I" to dictionary with Asterisk key, pop up says "this is already in the dictionary" but now when I press 4 once it's returning I in predictive

**Comment by sspanak** [comment]
Everyone, please try out the new [v27.0](https://github.com/sspanak/tt9/releases/tag/v27.0). I believe it fixes the bug, but please let me know if it still persists.
