### ISSUE TITLE
adding words with apostrophes only adds the portion before or after the apostrophe

### ISSUE THREAD

**Issue by justbruce** [sspanak/tt9#398]
for example, I've tried to add the word 'would've" and simply can't  It will allow "would" or "ve" but not "would've"

**Comment by sspanak** [comment]
This is a duplicate of #375.

But you shouldn't be adding such words to the dictionary. `'ve` `'s` and other contractions are available separately, so that you can combine them with any word. Just type `96853183` and you will get `would've`

**Comment by justbruce** [comment]
> This is a duplicate of #375.
> 
> But you shouldn't be adding `would've` to the dictionary. `'ve` `'s` and other contractions are available separately, so that you can combine them with any word. Just type `96853183` and you will get `would've`.
> 
> The problem with other words, such as "rock'n'roll", will be solved in the other issue.

It might be that it should work, but typing '9685313' results in "would,vd" instead of "would've'.  '8428155' yields "that,kl" instead of "that'll". 

  So something is malfunctioning

**Comment by sspanak** [comment]
Then make sure you are using the latest version and that you have re-loaded the dictionary to get some new words.

**Comment by justbruce** [comment]
"would've" now works with latest version.  "That'll and "It'll" don't.  

  Why can't we add our own contractions to the dictionary?

**Comment by sspanak** [comment]
> Why can't we add our own contractions to the dictionary?

Because they will mess up automatic word breaking and because they may appear instead of other suggestions. This is what has probably happened on your phone.

The other possibility is that it is lagging too much, which also produces incorrect suggestions sometimes.

Either way, both problems will be solved in the next release, which will also bring a lot of new English words. So please, be patient until then.
