### ISSUE TITLE
Qwerty Option

### ISSUE THREAD

**Issue by ScorpionOO8** [sspanak/tt9#406]
Hi, I want to start by thanking you for this open source T9 keyboard app. You're a real G 😎

I am wondering if it's possible to add a mode for displaying a normal qwerty keyboard while allowing the phone's physical T9 keys to do the predictive T9 thing alongside the onscreen qwerty layout. This allows for either input option depending on scenario.

Even better would be if there's a toggle on the onscreen keyboard to show or hide the qwerty layout (hiding meaning minimize the onscreen keyboard to just predictions and the toggle or something minimal). This would improve ease of use as sometimes the onscreen keyboard covers up most of the display on my not-too-smart phone.

Thanks for reading my request!

**Comment by sspanak** [comment]
Before answering your question, I would like to ask what _actually_ are you missing? I suppose it is not the layout itself, but sometimes you are missing words and need to type them faster. If this is the case, a big English dictionary update is coming in v27.0, so you may find much of what you are missing (I assume you use English, because you said QWERTY. Sorry, if I got it wrong). Please, wait until then. If you still find there are missing words, you could open a new issue pointing out a certain category, for example, exotic animals, river names, car manufacturers or whatnot. Or you could even suggest a word list. I really need a hand with this, especially for the languages I don't speak.

Now getting back to the question.

> I am wondering if it's possible to add a mode for displaying a normal qwerty keyboard while allowing the phone's physical T9 keys to do the predictive T9 thing alongside the onscreen qwerty layout... This would improve ease of use as sometimes the onscreen keyboard covers up most of the display on my not-too-smart phone.

It is possible, but it is not going to be more useful than any other QWERTY keyboard. As you have noticed, QWERTY is nearly unusable on 2-3" screens. I am even struggling typing on my 4.5" completely-smart-phone. The keys are way too small, yet it covers so much space, you can't see what you are typing. This is the second reason TT9 exists - it takes minimal space and it makes your phone usable. Adding a QWERTY layout kind of contradicts the philosophy, so sorry, this is not going to happen.

Another problem is, it is not just QWERTY. There are many derivatives for different languages, for example `QWERTZ` for German, `AZERTY` for French and many others having different special characters. Then come the non-Latin languages that have completely different layouts. Some languages even have more than one layout.

Adding all this is just too much work. Also given that there are many specialized (and open-source) keyboards that already do it quite good, I don't feel it is worth it.

I would suggest using TT9 together with some other keyboard and switching between them when necessary. If your phone provides an easy way of switching you could use that, if not, just assign the "Change Keyboard" function from the Hotkeys section and you'll be able to switch easily.

> I want to start by thanking you for this open source T9 keyboard app. You're a real G 😎

Enjoy! And spread the word if you will. :slightly_smiling_face:

**Comment by sspanak** [comment]
> This must surprise you, but I timed myself typing a sentence using the predictive T9 and the onscreen GBoard and I was actually 3x faster with the onscreen. Yes, it is tiny, but the fact that I don't have to put as much pressure on the touch keyboard as the hardware one to complete a key press, and the fact that the onscreen keys have less travel distance between them, and the fact that I don't have to search through chunks of ABC, DEF, ...XYZ to find my next key makes the qwerty layout faster for me. I have average to large male hands and the onscreen GBoard is freaking tiny, but somehow it works for me.

Well... if you feel so many advantages when using QWERTY, I don't think it is likely for you to find T9 more useful over time. 

From my perspective, I don't need to look for the letters on the nine keys. In fact, I don't even need to look at the screen, I can type while walking on the street and holding my hand in the pocket. While with QWERTY... I simply fail :laughing:. And I quickly give up using the phone. As for the speed, I don't know, I think I type fast enough. At least I don't have the feeling I'm slow. And I suppose that's the case for many people around here.

So, you see, you just may have different needs and forcing yourself to use the T9 way may be an unnecessary effort. In the end, it is up to you. :slightly_smiling_face:
