### ISSUE TITLE
Automatic capitalization not working

### ISSUE THREAD

**Issue by TenticalHead** [sspanak/tt9#414]
Hi there!
For some reason the automatic capitalization does not seem to work for me.
The option is checked, but it still isnt working. Any ideas?

Using it on a Qin F21 pro.

**Comment by sspanak** [comment]
Well, there is a general problem with the text case. Lowercase is forced in many cases, when it shouldn't. This is fixed in `master` and it will be released in the upcoming v27.0.

Another issue could be the dictionary itself. What language are you using? I know many words in many languages have the wrong text case. I have tried to fix most of them in English and some of them in Dutch and the updated dictionaries will be included in v27.0, too. Unfortunately, I lack the knowledge and the capacity to fix all words in all languages, so any help with this will be appreciated.

**Comment by TenticalHead** [comment]
Thanks for the quick response!
Iv been using English, Swedish and Finnish. With the predictive writing it works, but should it/will it work with "standard" keypad typing?

**Comment by sspanak** [comment]
All typing assistance works only in Predictive mode, when you are assumed to write text. All other modes are meant to allow you to type something exactly the way you want, without altering it. This is actually critical in some cases, for example, when typing passwords, URLs, money amounts and whatnot.

So, from what I understand, there is no technical problem, therefore no bug to fix.

Anyway, if you notice any misspelled words in any languages, you are welcome to open an issue or even a pull request to correct them.
