### ISSUE TITLE
v27 double presses

### ISSUE THREAD

**Issue by WallK** [sspanak/tt9#439]
I sometimes get double presses on letter inputs and changing the language

I can't find a consistent way to reproduce, but it happens sometimes when typing
Also, holding # to change the language sometimes also changes input type (to abc, for example)

This never happened in previous version
Maybe it's a combination of much faster input processing and lackluster debouncing on my phone?

Thank you

**Comment by sspanak** [comment]
Are you using a Qin F21 or a Cat S22 phone? Their keypads degrade over time and the multi-click becomes worse and worse. My F21 is almost unusable an year after I bought it. It either produces multiple presses, or it misses long press (like when changing the languages).

There is a big discussion about the hardware problem in #399 that you may want to check out. I have added a hack to remedy this. It will be part of v28.0, but if it is unbearable, you may want to use the APK attached in the other issue, while waiting.

**Comment by WallK** [comment]
Cat S22
But it's newish, couple of months old
It does not produce double numbers in dialer and it never did double letters in previous version, so I'm not sure it's hardware that's changed
Maybe slowish polling was just right for my phone (:

**Comment by WallK** [comment]
It's not very prominent, but reading the other issue -- it will happen to me sooner or later, so software debouncing will be a great feature, thank you!
<sub>Maybe we'll get old phone quality in a recent device some day...</sub>

**Comment by sspanak** [comment]
@WallK, v28.0 is out. Please try if the key repeat protection fixes the problem for you. If it is not really bad, you may want to start with a low value, for example: 30-50 ms, so that you would still be able to type fast.

> Maybe we'll get old phone quality in a recent device some day...

I am looking high and low for such a device. I still keep my old Nokia 3310 and use it as an example when I am not sure how to do something new. Unfortunately, I can only share the software goodness...

**Comment by WallK** [comment]
Trying it out! 30ms almost fixed it, going step by step and giving it a day to truly test
Thank you!

**Comment by WallK** [comment]
Left it on 50, no double presses for a day
The only annoyance is trying to erase something fast (:

**Comment by sspanak** [comment]
So your keypad has started deteriorating. :slightly_frowning_face: 

Since I was disappointed with my Qin F21 Pro, I was considering of buying a CAT phone, even though they are hard to find in my country, but unfortunately, they are no better.

> Left it on 50, no double presses for a day
The only annoyance is trying to erase something fast (:

Yeah, you have to find some middle ground. If it makes sense, I can easily add 40 ms. I just received very little feedback, so I decided to go with a list that is not too long, not to make people scroll a lot.
