### ISSUE TITLE
[BUG] No on-screen keyboard with On-Screen Numpad disabled

### ISSUE THREAD

**Issue by HarriBuh** [sspanak/tt9#448]
As the On-Screen Numpad is deactivated by default, I was wondering how I should be able to type with nothing to work with:

![Screenshot_20240302-111819.png](https://github.com/sspanak/tt9/assets/123186113/b0ee20e7-d700-4095-9c6a-d08412a2d69b)

I had to enable the BETA feature of the on-screen Numpad to make it finally appear:

![markup_1000006187.png](https://github.com/sspanak/tt9/assets/123186113/14dc1582-af28-49f5-af12-fca8741da192)

![Screenshot_20240302-112223.png](https://github.com/sspanak/tt9/assets/123186113/8e8644c4-05f9-4c9f-b371-4203297efa66)

Google Pixel 7
Android 14
Latest app version 28.0

**Comment by sspanak** [comment]
Well, the configuration out-of-the-box is meant to work on phones like this:

![qin-f21](https://github.com/sspanak/tt9/assets/27846105/275eb101-ca01-4d6f-a1e9-621e0df4048c)

and not phones like this:

![google-pixel7-pro-2-800x800](https://github.com/sspanak/tt9/assets/27846105/942d7245-1712-4002-be34-81ee93f3144d)

In order to type on the former, the virtual keypad is not needed, so it is disabled by default.

I don't know how to put it any other way. :slightly_smiling_face:
