### ISSUE TITLE
Cannot Enable TT9 on Kyocera DuraXV Extreme+

### ISSUE THREAD

**Issue by geewrd** [sspanak/tt9#455]
I upgraded from the DuraXV Extreme to the *plus* version (E4811). I was able to install the TT9 APK I had been using on my older DuraXV (4810), but it had a few issues, specifically the down button bug made it annoying to use. So I downloaded the latest TT9, and installed it. However I am unable to enable the keyboard. The status always shows as disabled, and when I open the *Manage Keyboards* screen, I cannot select anything, and only the default keyboard is showing.

Any idea how to move past this? The built in predictive text on the 4811 is almost unusable.

I can try to upload some screenshots if that would be helpful.

**Comment by theancientways** [comment]
I feel your pain, I tried using the DuraXV Extreme Plus's native texting software and it was abysmally bad to the point of being unusable. That's what initially led me to find TT9. I used an older version of TT9 on the DuraXV Extreme Plus and it worked perfectly, then I switched to the Sonim XP3plus which I think is just a better all around phone (way better battery life and larger screen). Maybe there is a compatibility issue with the current version of TT9 but I'm sure sspanak will help you out. He's very responsive to bug reports and requests, just be sure to support him to keep this project going and give him more incentive to continue to give it his attention.

**Comment by sspanak** [comment]
The problem has been discussed [here](https://github.com/sspanak/tt9/issues/198). Some manufacturers prefer to lock their device and disallow installing or enabling (or both) third party keyboards or apps in general. It is likely to reduce the complaints "my phone isn't working", caused by the manually installed apps.

If so, you will have to connect your phone to a computer and use a program called "adb" (Android Debug Bridge). If you feel confident using the command-line, follow the instructions below:

1. Go through the [adb quick setup](https://www.xda-developers.com/install-adb-windows-macos-linux/). If you need more detailed info, see the [developer documentation](https://developer.android.com/tools/adb).
2. If your phone permits installing APKs, skip this step and install normally. Otherwise, install using:
```bash
adb install /path/to/apk/on/your/computer/tt9-vXXX.apk
```
_If you are installing a new version over an older one, you may have to uninstall the old one first. See below._

3. Enable Traditional T9:
```bash
adb shell ime enable io.github.sspanak.tt9/.ime.TraditionalT9
```

That's it! TT9 should appear the next you start typing.

To uninstall, do:
```bash
adb shell pm uninstall io.github.sspanak.tt9
```

Hope that helps!

P.S. I guess it is a good idea to include these instructions in the documentation.

**Comment by geewrd** [comment]
> The problem has been discussed [here](https://github.com/sspanak/tt9/issues/198). Some manufacturers prefer to lock their device and disallow installing or enabling (or both) third party keyboards or apps in general. It is likely to reduce the complaints "my phone isn't working", caused by the manually installed apps.
> 
> If so, you will have to connect your phone to a computer and use a program called "adb" (Android Debug Bridge). If you feel confident using the command-line, follow the instructions below:
> 
> 1. Go through the [adb quick setup](https://www.xda-developers.com/install-adb-windows-macos-linux/). If you need more detailed info, see the [developer documentation](https://developer.android.com/tools/adb).
> 2. If your phone permits installing APKs, skip this step and install normally. Otherwise, install using:
> 
> ```shell
> adb install /path/to/apk/on/your/computer/tt9-vXXX.apk
> ```
> 
> _If you are installing a new version over an older one, you may have to uninstall the old one first. See below._
> 
> 3. Enable Traditional T9:
> 
> ```shell
> adb shell ime enable io.github.sspanak.tt9/.ime.TraditionalT9
> ```
> 
> That's it! TT9 should appear the next you start typing.
> 
> To uninstall, do:
> 
> ```shell
> adb shell pm uninstall io.github.sspanak.tt9
> ```
> 
> Hope that helps!
> 
> P.S. I guess it is a good idea to include these instructions in the documentation.

Thank you so much! I'm now a little ashamed I didn't realize I could use ADB to manage keyboards.

I really appreciate your work, and your quick responses.
