### ISSUE TITLE
Delete function missing

### ISSUE THREAD

**Issue by rarityminsk** [sspanak/tt9#470]
Hello, I'd like to delete some specific words I never use in my native language and furthermore personnalize the emojis available on the dictionnary, however I couldn't find such an option in the settings. There's only "Delete unselected" or "Delete all", which isn't what I wish for. I looked up the guide, there's apparently an export and delete function that does not appear in my settings. Is there something I'm missing?

Thank you for your time.

**Comment by sspanak** [comment]
The new stuff is available in [v29.0](https://github.com/sspanak/tt9/releases/tag/v29.0). If you are using the Github version, install it from the link. Otherwise, you will have to wait for about a week until it appear in F-droid.

Have in mind you can only delete the words you have added with the Add function. It is not possible to delete factory words.

Also, if you think there are misspelled, wrong or otherwise unusable words, you are welcome to report them. I don't speak all the supported languages and even if I did, it would have been impossible for me to verify every single word in every language. User contributions are most helpful in this regard.

**Comment by rarityminsk** [comment]
This new version indeed add the delete and export functions and it also seems to have fixed the unusable words I had, however I am not able to register special characters anymore, so I can not add personnalized emojis to the dictionnary like before

**Comment by sspanak** [comment]
>  I am not able to register special characters anymore, so I can not add personnalized emojis to the dictionnary like before

Do you mean all special characters or some specific emoji? Adding words is restricted to actual words consisting of letters and emoji. However, detecting emoji is a bit difficult and I might have missed something. This is why I am asking for an example.

Or do you mean you can not add words at all? Of so, please check #456. You may be experiencing the same problem.

**Comment by rarityminsk** [comment]
I can add words but not special characters. For exemple, if I try to add ":/" or a more detailed emoji like "＼(★^∀^★)／", it won't detecte it as an actual word. If I try to add ":DDD", it will only add "DDD" to the dictionnary. If I am not mistaken, the older versions of the programm could detect special characters.

**Comment by sspanak** [comment]
Oh, I am not even sure what "＼(★^∀^★)／" is and I didn't know this is considered an emoji. And yes, special characters are restricted for security reasons. It might have been possible to add just anything in early versions of TT9, but not anymore.

I may consider a new category of added words, for example, "special chars" or something, where one could add emoji like the ones you mention, as well as email and other non-word words.

But anyway, this is the fourth topic we are discussing here and it has nothing to do with the title. There is nothing to do regarding the original questions, so I am considering the issue done.

If you would like to request a new feature, like adding those special char emoji, please create a new issue, just for that. Let's keep the board organized.
