### ISSUE TITLE
Feature Request: Import wordlist

### ISSUE THREAD

**Issue by DarthFlip** [sspanak/tt9#472]
Now that in version 29 you can export your custom words, can you add a way to import the csv file?

**Comment by maverick74** [comment]
maybe, even if it's still a csv file, using a personalized extension (e.g.: user.tt9 instead of user.csv) could somehow avoid importing a list that was not generated/accepted by tt9

(just an idea, not sure if it's any good...)

**Comment by sspanak** [comment]
Well, the extension makes no difference, the users will still be able to put what they want in the file.

Besides, I would like to promote the open-source idea where everyone could help making the project better, instead of everyone making and using their own mods.

**Comment by maverick74** [comment]
> Well, the extension makes no difference, the users will still be able to put what they want in the file.

Yeah, that was the whole idea of changing the extension. It would still be a CSV file that anyone could edit, but having an _unknown_ extension maybe it would scare _newbies_ from it, and leave mostly just those who "should know what they're doing and how to deal with it"

> Besides, I would like to promote the open-source idea where everyone could help making the project better, instead of everyone making and using their own mods.

my idea is not much in this spirit, i know... :p

All in all, being able to have a backup/list of the words added is already great. One just have to open it and add the words - which in my case are not that much - to tt9, in case one have to reinstall.

**Comment by maverick74** [comment]
can i just erase that last line in my last comment?!........

I was about to switch from the "full" version to the "lite" version (for space reasons) until... i exported my personal dictionary and found that i have 123 added "words"........ (not as few as i thought they were...)

just thinking that i'll have to add that many manually is making me think twice about it...

**Comment by maverick74** [comment]
Sharing workaround:
I've opened the exported .csv directly on the phone, placed the cursor inside each word and added it!!!

Was the fastest/easiest way to do it... ;)

**Comment by sspanak** [comment]
You can install the "lite" version over the "full" version and vice versa, you don't have to uninstall anything before that. They are identical except for the missing language files. Did your phone refuse the operation?

**Comment by maverick74** [comment]
> You can install the "lite" version over the "full" version and vice versa, and preserve all words and settings, you don't have to uninstall anything before that. They are identical except for the missing language files. Did your phone refuse the operation?

I did that and it actually went ok!!! 
But, since the previous version had all the dictionaries included, i was left wondering if the lite would erase the "unused dictionaries" or if they would be kept on the phone, since they were already installed (i even cleared the dictionaries not used)...
 however, at the "end of the day" i choose to play safe and remove it completely to reinstall the lite version...
(i suppose that now i only have portuguese and english in my phone... ???**_how can i be sure_**???)

> Also, I am curious, why don't you want to share the words so that I can include them in the general dictionary? Have you added passwords or something?

Nooooo!!! No passwords are saved on my phone anywhere! That's a big mistake!!! No!!! ahahah 
I'm not _that_ stupid ahahah

i have no problem in sharing the "words" i save, the problem is that _technically_ they are not words and do not belong in a dictionary!

**i'll share a few examples:**

**Real Word** ---------------vs------------- **what i use / added to the dictionary:**

thanks----------------------------------------------------tks
what the f***------------------------------------------wtf
comigo---------------------------------------------------cmg
fim de semana----------------------------------------fds
qualquer------------------------------------------------qq
depois---------------------------------------------------dps
hoje-------------------------------------------------------hj

I use lots of words like this (and a bunch of some "ugly words" that are quite common)...

but none of them belong to a dictionary (hence why i don't ask them to be added), but i use them A LOT ahahahah

(**by the way... should i open a bug report to submit some word corrections??? I have a bunch of the that are capitalized and shouldn't be...**)

**Comment by sspanak** [comment]
> But, since the previous version had all the dictionaries included, i was left wondering if the lite would erase the "unused dictionaries" or if they would be kept on the phone, since they were already installed (i even cleared the dictionaries not used)...
however, at the "end of the day" i choose to play safe and remove it completely to reinstall the lite version...
(i suppose that now i only have portuguese and english in my phone... ???how can i be sure???)

There was only one case when I had to wipe out everything, in v27.0. I don't think I'll have to do this ever again, so rest assured all you have is preserved as is on every upgrade. And if there is need to delete words again, there will be an announcement in the release notes.

Btw, I am planning to put the languages on a separate screen and display some more information about them. Thanks to what you said, I realized there must be some indication if the dictionary is deactivated, but the words are loaded, so you don't have to guess.

> Nooooo!!! No passwords are saved on my phone anywhere! That's a big mistake!!! No!!! ahahah
I'm not that stupid ahahah

Good thinking! :smile: 

> i have no problem in sharing the "words" i save, the problem is that technically they are not words and do not belong in a dictionary!

Got it. On the other hand, everyone uses "wtf", so I think it is OK to add it.

**Comment by maverick74** [comment]
> > But, since the previous version had all the dictionaries included, i was left wondering if the lite would erase the "unused dictionaries" or if they would be kept on the phone, since they were already installed (i even cleared the dictionaries not used)...
> > however, at the "end of the day" i choose to play safe and remove it completely to reinstall the lite version...
> > (i suppose that now i only have portuguese and english in my phone... ???how can i be sure???)
> 
> There was only one case when I had to wipe out everything, in v27.0. I don't think I'll have to do this ever again, so rest assured all you have is preserved as is on every upgrade. And if there is need to delete words again, there will be an announcement in the release notes.
> 
> Btw, I am planning to put the languages on a separate screen and display some more information about them. Thanks to what you said, I realized there must be some indication if the dictionary is deactivated, but the words are loaded, so you don't have to guess.
> 
> > Nooooo!!! No passwords are saved on my phone anywhere! That's a big mistake!!! No!!! ahahah
> > I'm not that stupid ahahah
> 
> Good thinking! 😄
> 
> > i have no problem in sharing the "words" i save, the problem is that technically they are not words and do not belong in a dictionary!
> 
> Got it. On the other hand, everyone uses "wtf", so I think it is OK to add it.

Yes... there are a few ones in English everyone uses... wtf, omg, lol, and so on (English is the king of abbreviations ahahah)! 

Oh and if it's not asking too much, please add "KDE" as well ( that Linux brand from KDE.org )

around here _I have the feeling_ this is more kind of a generation-specific thing! 
Kind of "Ever had a Nokia? Then you know about the abbreviations"! 
But then again... I may be wrong and it may also be just my view of it...

**Comment by sspanak** [comment]
This issue is about importing words. For missing/incorrect Portuguese words, could you please update #548? I would like to keep things organized, so I can easily find all the info on topic in one single place.

I don't mind adding technical terms, commonly used acronyms and whatnot. In fact, I think it is a great idea. It is just I don't use all the 29 languages every day, so I have no idea what is missing.

> around here I have the feeling this is more kind of a generation-specific thing!
Kind of "Ever had a Nokia? Then you know about the abbreviations"!
But then again... I may be wrong and it may also be just my view of it...

Of course, I've had a Nokia. I still keep my old 3310 and when I don't know what is the best way of doing something, I turn it on to get an example how things are done. Traditional T9 is largely inspired by the 3310. This is why it works so good most of the time. :stuck_out_tongue: 

The thing is my primary language is Bulgarian. We have a different alphabet, we don't use acronyms as much, instead we prefer long words (not as much as Germans, though!), so in this perspective I am missing a lot.

As for importing words, I may reconsider my position. But if I do it, will be possible to import only words consisting of letters. Meaning, no words like "I'm", "what's", etc... And probably limit the list to 1000 or something.

**Comment by maverick74** [comment]
> I don't mind adding technical terms, commonly used acronyms and whatnot. In fact, I think it is a great idea. It is just I don't use all the 29 languages every day, so I have no idea what is missing.

> ( thinking outloud: _"acronyms"... how I searched the back of my memories for it before I use "abbreviations"... well moving on..._ ) yeah, naturally you can't know all the acronyms of all languages!!! It would be awesome anyone could ahahah

> > around here I have the feeling this is more kind of a generation-specific thing!
> > Kind of "Ever had a Nokia? Then you know about the abbreviations"!
> > But then again... I may be wrong and it may also be just my view of it...
> 
> Of course, I've had a Nokia.

That was not a question! It was an example!!! Ahahah. You could not have built tt9 if you hadn't had contact with Nokia! It would be almost impossible to emulate it so well if you didn't own one ahahah!

My point was that - around here - most people who use acronyms where also Nokia users and that - from my experience - younger generations don't use acronyms so intensively as the Nokia generation! (this is my idea, from my experience! I could be wrong)

> As for importing words, I may reconsider my position. But if I do it, will be possible to import only words consisting of letters. Meaning, no words like "I'm", "what's", etc... And probably limit the list to 1000 or something.

Yeah! I'm perfectly ok with that! That would work!

**Comment by maverick74** [comment]
Horaay!!! XD

Thank you!!!

What's the limit? 1000?

**Comment by maverick74** [comment]
Per file? You mean you can't have a 1000 words file and instead have to import 4 files of 250 words each?

Was a 1000 file too much bloat?

**Comment by sspanak** [comment]
> Per file? You mean you can't have a 1000 words file and instead have to import 4 files of 250 words each?

Excactly.

> Was a 1000 file too heavy?

In a way, yes. I have a low-end, 8-core/4 Gb/64 Gb touchscreen phone, comparable to a high-end button phone. It is able to import about 10 words per second. It is much slower than importing the factory dictionaries, because I am running many extra validation steps, to ensure no one can shoot themselves in the foot by trying to import a book, or an image file or the same word 11000 times.

But, I am not so worried about the importing itself. It is the typing speed that concerns me. The custom word storage is not designed to handle large amounts of data. I haven't tested what are its limits, but I know it has the potential to cause a lot of lag. Even more than the versions before 27.0. Because of this, I wanted to discourage people to import too many words and came up with the mentioned limits.

**Comment by maverick74** [comment]
You got me curious about this (i had in mind 250 would be more than enough for me), but... just to be sure i went on to see the number of words i've added so far

... 173 ... 

i never though i had so many!!!

(i have a few words that are english words i added to the portuguese dictionary, however, to avoid switching language all the time... the language switch key is a bit out of hand for "right hand typing")

**Comment by maverick74** [comment]
i'll organize what i can and i'll send some that may be worth adding

**Comment by sspanak** [comment]
> You got me curious about this (i had in mind 250 would be more than enough for me), but... just to be sure i went on to see the number of words i've added so far
... 173 ...
i never though i had so many!!!

That's OK, you can still add 837 more. And if you need to migrate to a new phone, you will just have to split the exported file into 250-word files

Thanks for suggesting the new words. I'll definitely add them.
