### ISSUE TITLE
Auto-accept custom timeout?

### ISSUE THREAD

**Issue by Niiisse** [sspanak/tt9#474]
Love this app, thanks for picking up the development.

Simple question: the default timeout of 800ms is way too slow for me to comfortably type. Is there any way for me to lower this timeout to 300ms? Is this something that could be added as an option in settings?

Thanks!

**Comment by sspanak** [comment]
> Is there any way for me to lower this timeout to 300ms?

It is not possible if using the app normally. 

But if you know the timeout is 800 ms, you must have review the source code. If you feel comfortable with building your own APK, just change 800 to 300 in `SettingsStore.getAbcAutoAcceptTimeout()`, build and install. Just keep in mind you must uninstall the official APK before installing yours, due to Android security policies. Also, if you would like to go back to the Github or F-droid version, you will then have to uninstall yours.

> Is this something that could be added as an option in settings?

Yes, it should be fairly easy to do.

**Comment by Niiisse** [comment]
> But if you know the timeout is 800 ms, you must have review the source code. If you feel comfortable with building your own APK, just change 800 to 300 in `SettingsStore.getAbcAutoAcceptTimeout()`, build and install. Just keep in mind you must uninstall the official APK before installing yours, due to Android security policies. Also, if you would like to go back to the Github or F-droid version, you will then have to uninstall yours.

I actually saw you mentioning this in another issue, but it sounds very doabe. I've never built an Android app before, but I'm sure I'll figure it out. Thanks for the suggestion!

One more question - let me know if I should open a new issue for this - new sentences don't get automatically capitalized in abc mode. Is this intentional or a bug?

**Comment by sspanak** [comment]
> One more question - let me know if I should open a new issue for this - new sentences don't get automatically capitalized in abc mode. Is this intentional or a bug?

You get typing assistance only in Predictive mode, while ABC is entirely up to you. It is intended for typing emails, URLs, passwords and other technical stuff, where having the control in your hands is better.
