### ISSUE TITLE
Feature request: Sentence character order selection tweaks OR provide mechanism to change sentence character precedence

### ISSUE THREAD

**Issue by wazroth** [sspanak/tt9#498]
One frustration I have with the app is that many of the common sentence characters available under "1" are deep in the menu. I am sure this varies from language to language, but in particular in English I find the `';:"!?` (12th-17th positions) to be _very_ commonly used and _very_ inconvenient to access, especially as compared to characters like `[]§~`, which with the exception of `~` for approximation I've never used on a phone (and I don't think I've ever seen `§` offered on a phone, even in an extended-characters menu). (I recognize that you can scroll backwards to get to the question mark, etc., but even things like `'` are quite distant compared to, say, the square brackets.)

Anyway I see from #329 that this item has come up before, and although that one is tagged #wontfix I thought I'd bring it up again since it's a major inconvenience in an otherwise great app. And of course I can't speak to the character prevalence in languages outside English, but at least for most Latin-alphabet languages I wouldn't expect huge variation. In that light, I do think a reevaluation of the coded order is worth considering. A truly optimal solution would be to provide an interface where we can set an order,  but I realize that that would be much more work. (I don't think dynamic ordering makes sense here, as I think you've considered and rejected.)

**Comment by sspanak** [comment]
The character order can be changed per language, it is not a problem. So, let's talk about English. At the beginning, I looked up some frequency tables and I tried to order the punctuation in a meaningful way. But, English is not my primary language. I don't use it much and I can't tell if the order is really OK. I only know it feels fine for occasional typing.

From the perspective of a native speaker it may be inconvenient, but what _exactly_ is inconvenient?

Is that `'` is too far away? If so, this is intentional. Yes, the apostrophe is used a lot in the English language, but in most cases, you don't need to select it explicitly. If you want to type "I'm", just press "416", without explicitly selecting the apostrophe. Same for "don't", press "36618" and you'll get it. No scrolling, no nothing. You may have noticed the contractions are available as separate "words" for easy combining with anything. You can even make nonsense combinations like "I're" (4173) if you want.

Pretty much, you shouldn't need to select `'` most of the time. But if I am wrong, please, provide examples to help me understand better.

Or, option B, are all characters inconveniently ordered? In that case, could please suggest a better ordering. I would like to preserve the most frequently used characters being in both directions, but other than that, I am open to new ideas.

P.S. I've noticed @TomJansen also gave thumbs up. Tom, you are welcome to suggest improvements for Dutch, too.

**Comment by wazroth** [comment]
I do think there's a broader order problem. Between the 1 and the 0 I think that, for English at least, all ASCII punctuation ought to be available at a minimum. With that in mind I'd propose: 

1:
`.,?!"'()\`@#/%&-;:`

0:
`[CR]=+<>^~\\{}[]*`

0-more:
`$` etc. 

Rationales: 
List 1 is meant to include characters that might come up in typical text. I've tried to left-bias (my perception of!) the most common characters while putting the second-most common characters right-biased, with lesser-used items in the middle. The left-biasing is a little stronger than the right-biasing to account for the user-interaction preference for right-scrolling. Apostrophe/single quotation makes the cut as a common character because it does appear in words in places outside of contractions with some frequency (in the US, especially in names), and in British English it's often used for the outer quotation mark (unlike in American English which uses the double quotation mark). I've moved @, #, and / here due to their common use in internetty things like hashtags, email addresses, and URLs; having them easily accessible seems wise, though I could see an argument for moving them back to the 0 menu. I could also see an argument for doing this with the  back-tick (`\``) though some people (heaven bless them) use this for the open quotation mark for some reason, which is why I included it in list 1.

List 0 is basically everything else; you could think of this as the "math symbols" with the exception of ones that are frequently used in regular typing such as the percentage sign, hyphen, parentheses. I also put the carriage return here because it's not super frequently used in text, though it's used enough that it should continue to be the first choice when 0 is selected; having it as the first item in a menu makes it nicely available.

0-more is already defined to have a special purpose so I am not proposing changes there. It is a bit weird that monetary symbols feel so "remote" but I understand that this is doing a lot of work to support a highly internationalized package.

There are probably non-ASCII symbols that could be included but I can't think of ones that are super relevant for English; these could go in the 0 menu.

This isn't particularly vetted by data but I think it gets closer than the current arrangement.

**Comment by sspanak** [comment]
Well, if I am to move characters between the two keys, I'll have to do so for all languages. 0-key is not customizable, so I must ensure there are no missing special characters. People may need them for typing passwords. This is also important. But I don't think it is going to be a problem. Your suggestions are quite logical and should make sense for all languages.

There are just two things I do not agree with. To me, the comma must come first. It is the character I use the most and I would like to be able to access it without extra clicks. Then, it's the left-right distribution. I am not biased toward scrolling in either direction, but I rather prefer quick access, meaning equal frequency distribution on both sides.
However, I do understand we both have personal preferences, and there are probably people with different preferences.

I propose the following.

First, let's move some characters from 1-key to 0-key and back, as you suggested. Your lists do make more sense. I like them.

As for the order, I do not want to make it automatic. Unlike words, punctuation is easier to remember when it is static. Muscle memory works better when you know "right-right" produces a question mark and "left-left-left" is an apostrophe, for example. When typing words, there are many, many more combinations, so it is more convenient to see the most likely one at the beginning of the list.

How about making the character lists customizable? People, who are fine with the default order, will keep using it and live their lives.

But for people who do care, I can add a text field in the settings, where you can type the characters in the order you want. It may even be possible to remove some of them if you don't care about them. Perhaps, it could even be possible to move a character to another key. Even though `'`, `"` and `-` must remain on 1-key and Space and Newline must be on 0-key for technical reasons. Or... I can think about moving and removing. I am not entirely sure how it will impact everything.

To complete the picture, there can be a "reset" button if you mess up the lists too much.

> It is a bit weird that monetary symbols feel so "remote" but I understand that this is doing a lot of work to support a highly internationalized package.

There weren't infinitely many options. I didn't and I still do not want to make huge lists, because it will be overwhelming when trying to find the character you need. I wanted to separate the currency symbols into their own group. Then I had to come up with a key combo for accessing them, which was also a challenge because I had limited options. Many phones have just 0-9, "#" and "*" and also there's the on-screen keypad. This was the most universal solution I came up with. If you have a better idea, please share it.

> There are probably non-ASCII symbols that could be included but I can't think of ones that are super relevant for English; these could go in the 0 menu.

I've included the characters that can be found on most keyboards, including physical computer keyboards. I think we are good from this perspective. It is not a keyboard's job to offer any character. There are specialized apps for that.

> I could also see an argument for doing this with the back-tick (`) though some people (heaven bless them) use this for the open quotation mark for some reason, which is why I included it in list 1.

Some even use it as an apostrophe, which is absolutely horrible, in my opinion. But who am I to judge...

**Comment by wazroth** [comment]
- I think having `,` first is fine, especially with the double-0 shortcut available for`.`. 
- I do think (speaking as a UX professional) there's a definite human-factors bias towards right-scrolling, at least in LTR languages, but I'm sure users could get used to left-scrolling for common items. I think my bigger concern here is that the availability of left-scrolling from the menu start is not necessarily obvious and might not ever be discovered by a user. This doesn't necessarily mean that any left-scrolling emphasis should  be avoided, but it might be worth keeping in mind. Is it possible to hint in the UI that there are items to the left of the starting position? Maybe make the list more explicitly circular instead of snapping back to the far left when scrolling off to the right? I'm sure as a subtlety of interaction design this would be more work to implement, though.
- I don't think that dynamic ordering makes any sense, for the exact reason you describe.
- Having a well-thought-out default order but making it customizable would be a great solution, if it's not too much work. If this seems feasible from the development standpoint I'd be all for it!

As far as other ideas for more expansive approaches: a lot of phones (including the default XT9 implementation from the XP3) have 1-key options similar to TT9, but also a provision to pull up a larger (full-screen or almost full-screen) menu with an exhaustive list of high-level ASCII or Unicode symbols, emoji, etc. Some of these interfaces have nested menus so you can navigate to the right flavor of symbol quickly. This is a whole other scope of work, though, and I'm not sure how well it would play with the existing UI implementation.

All the above notwithstanding, I think some character-ordering adjustments alone would be a good start, and everything else would be a bonus.

**Comment by sspanak** [comment]
I was thinking of creating a full-screen panel for character selection, but it seemed too difficult to do, so I went for the multiple lists on 0-key and 1-key. This approach is more consistent with what the rest of the keys do, so I thought it was the perfect choice.

> I do think (speaking as a UX professional) there's a definite human-factors bias towards right-scrolling, at least in LTR languages, but I'm sure users could get used to left-scrolling for common items. I think my bigger concern here is that the availability of left-scrolling from the menu start is not necessarily obvious and might not ever be discovered by a user. This doesn't necessarily mean that any left-scrolling emphasis should be avoided, but it might be worth keeping in mind. Is it possible to hint in the UI that there are items to the left of the starting position? Maybe make the list more explicitly circular instead of snapping back to the far left when scrolling off to the right? I'm sure as a subtlety of interaction design this would be more work to implement, though.

Speaking as an experienced web developer, I must say, Android is not flexible at all, when it comes to doing custom layouts or custom UX in general. You have the standard components (the suggestion list is called a RecyclerView) and trying to customize them is very time consuming or difficult, at least compared to what you can do with HTML+CSS. Maybe it is because I don't have so much experience with Android, or maybe Google didn't want developers to stray away too much from the standards, I don't know. Either way, I am not too fond of customizing the UI any more.

I very much like the idea of providing a setting for the user to rearrange the characters based on their liking. It sounds easy to do and it is probably what I will go for.
