### ISSUE TITLE
Not an issue: Tested and working perfectly on a Fretted Mode 1 Retro 2

### ISSUE THREAD

**Issue by ivanthetolerable1** [sspanak/tt9#502]
Just thought I'd share that I've been using this for 3 months on my FreeTel Mode 1 Retro 2 and it works no issues.

**Comment by sspanak** [comment]
Excellent!

In the upcoming version 31, I have made some improvements to officially support Android 13, rather than going into compatibility mode. It would be great if you confirm everything is still OK when it comes out.

Apart from that, is the keypad working well? So far, all phones that I have tested, except for Sonim XP3800, have terrible keypads. At first, they are fine, but after a couple of months of normal use, they start repeating or ignoring clicks. And with time, you have to press them harder to work.

Also, does the phone come with an APK installer, or the only way of installing apps is via a computer and ADB?

**Comment by ivanthetolerable1** [comment]
The phone runs Full Android 13 so no adb loading is needed. I did have to set the keyboard replay to 30 to make it work. So far, all apps but MS Teams work no issue. Teams likes to select and deselect the keyboard over and over. The solution is to open the app switcher and then go back into the app. 

It's a fairly pricy phone so I hope it holds up lol. 

Phone has native apk installation.

**Comment by sspanak** [comment]
v31.0 is officially out. I have tested it on a friend's phone and it looks fine, but please let me know if you find any issues with it, especially with the notifications.

As for MS Teams, you may have experienced #490. It was quite of a problem, but it was fixed in v31.0. In case something is still not right, check the [troubleshooting notes for Xiaomi](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#general-problems-on-xiaomi-phones) in the manual. You phone may also have custom permissions, that affect TT9 in a similar way.

**Comment by sspanak** [comment]
@ivanthetolerable1, are you still having problems with MS Teams? Shall we close this issue?

**Comment by ivanthetolerable1** [comment]
Hey, sorry to open this issue again. I was on vacation and didn't use MS teams in a while. I noticed that there's still the issue when I open a chat and press the text box, no keyboard pop ups or works. When I switch between apps, pressing home quickly twice, and return to Teams the box appears. This has to be done whenever I select a new message to someone. I upgraded from 31 to 34 and the issue is still there. 

Not a huge deal.

**Comment by ivanthetolerable1** [comment]
On some devices, TT9 may remain invisible, no matter what you do. In such cases, you have to enable [Always on Top](https://github.com/sspanak/tt9/issues/502#always-on-top)."

This didn't change anything btw.

**Comment by sspanak** [comment]
"Always on Top" is for phones without a touchscreen. It will definitely do nothing for you.

Unfortunately, I can't test MS Teams. I can't create a personal account. I guess I'll try again in the future, if I start working in an organization where they use it.
