### ISSUE TITLE
Pressing backspace should bring suggestions back

### ISSUE THREAD

**Issue by zkrx** [sspanak/tt9#534]
When typing fast, it's easy to press space while the wrong word is being suggested. My reflex is then to press backspace expecting to get suggestions back.  Unfortunately, nothing happens and one needs to erase the entire word and type the word again.  From my memory, old Nokia phones from 2008 behaved like what I'm expecting. How hard would it be to implement such a feature?

## Upvote & Fund

- The repository is using [Polar.sh](https://polar.sh/ddimo) so you can upvote and help fund this issue.
- The funding is received once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund the backlog.

<a href="https://polar.sh/sspanak/tt9/issues/534">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sspanak/tt9/issues/534/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sspanak/tt9/issues/534/pledge.svg">
</picture>
</a>

**Comment by sspanak** [comment]
This is called "word recomposing". 

It is not difficult to implement it, but at first I was concerned about performance, so I decided not to do it. It's the only reason, really. But since the optimizations in v27.0, this is no longer a problem.

Challenge accepted. I just need to find free time to do it.
