### ISSUE TITLE
Keyboard missing on contacts

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#549]
On the Xiaomi redmi 12c contacts' app (Yeap!!! It's specific to this app!) the keyboard fails to load after updating to 34!

I've tried different configs including forcing it to keep on front! Nothing worked!!!

Downgrading to 33 solves the problem!

**Comment by sspanak** [comment]
I need some extra information to fix the problem. Please do the following:
- Open the TT9 Settings
- Scroll down the version information and tap on it. This will open a screen called Debug Options.
- Find the "Log Level" option and change it to "Info"
- Go to the Contacts app. It doesn't matter if you type anything, just make sure the input field, where you want to type but you can't, is focused.
- Go back to TT9 Debug Options
- Scroll down to the logs list. You should see something like:
```
05-17 18:28:58.111  9218  9218 I tt9/KeyPadHandler: ===> Start Up; packageName: com.android.dialer inputType: 3 actionId: 0 imeOptions: 1073741830 privateImeOptions: null extras: null
```

Please send me a screenshot of all lines containing " ===> Start Up;" or copy and paste them here. You can tap the logs to copy them. The package name of the app may differ slightly, for example: `com.google.android.dialer`, or it may be entirely different, like `com.xiaomi.dialer`, I don't know. 

Also it may end with `.contacts`, instead of `.dialer`. In this case, please, also go to the the app, where you can dial a number (if it is a different one). I will need the package name and the input type, when you have clicked on the phone number field.

If you don't see any logs, try changing the "Log Level" to "Debug" and repeat the procedure. If you still don't see any logs, I'll try to explain how to obtain them using the command-line.

**Once you are done testing, do not forget to restore the "Log Level" to "Error"**. Otherwise, the logs will take up a lot of storage space and my cause TT9 to lag.

**Comment by maverick74** [comment]
"Xiaomi" "22126RN91Y"

![Logs](https://github.com/sspanak/tt9/assets/14912461/e5688582-d029-4641-ab71-ddb5263b62c2)

is this it?

**Comment by sspanak** [comment]
Yes, it looks like it. And it must be one of those Xiaomi tricks again. 

I'll prepare a testing APK for you, like the previous time. You will be able to upgrade to and from it normally, there will be no need to uninstall. I just need some time to figure it out.

**Comment by maverick74** [comment]
> Yes, it looks like it. And it must be one of those Xiaomi tricks again.

This time i've checked all permissions before i filed this bug report and none solved it...

> I just need some time to figure it out.

I'll keep it in v33 in the meanwhile

**Comment by maverick74** [comment]
Hi.

Only the "**Detect Phone Name**" works!

**Comment by maverick74** [comment]
> Maybe you haven't noticed it?

yeah, that's possible, yes!!! :)
