### ISSUE TITLE
[Request] On-screen Layout -> Full Keyboard QWERTY

### ISSUE THREAD

**Issue by jalius** [sspanak/tt9#553]
Hi,

I am using this keyboard app on my Cat S22 flip phone and I am loving it so far. This phone has a 12 key physical input.

A feature that I am interested in is to have an on-screen QWERTY keyboard which would allow me to use the touchscreen when necessary (passwords, uncommon search terms, etc.), while being able to use the physical 12 keys as the main input method.

This would give users maximum optionality between QWERTY and the physical 12 keys.

Is this a feasible change? Has this change been considered before? Do others think this change will be useful?

Thanks!

**Comment by sspanak** [comment]
It has been requested [at least once](https://github.com/sspanak/tt9/issues/406), as far as I remember. My position is still the same. Traditional T9 is a T9 keyboard and it will remain like this. Sorry, I will not fulfill this request.

I know using the ABC mode for typing passwords and non-words takes a bit more time, but it is what it is.

I suppose, when you say QWERTY, you are thinking only about the English keyboard layout. However, there are, for example, QWERTZ in German, AZERTY in French. Also, almost all languages have special characters, so I'll have to add support for that. And then come the Cyrillic languages that have entirely different layouts. It's just too much work. And I am not willing to invest time doing it.

One more time, I would recommend keeping another full-sized (QWERTY) keyboard and switching to it when needed. TT9 makes it easy. Just use the `✱`, `0-key` combo and select between all the installed keyboards. If you have Gboard, you can also do the same by holding the language key.

**Comment by maverick74** [comment]
> A feature that I am interested in is to have an on-screen QWERTY keyboard which would allow me to use the touchscreen when necessary

Because, sometimes, to manually type weird (totally-not-)words it can be faster in a QWERTY keyboard I'll leave the suggestion to use as alternative the **Unexpected Keyboard**

once installed (using the on-screen keypad), just long-press the keyboard key to select it! Coming back it's even faster by just sliding your finger on the FN key!

(sorry, no idea how to do it on a real keyboard!)

maybe having an easier/faster way to switch to the last keyboard - like in the unexpected keyboard (sliding left, for example) could be a solution for this cases @sspanak

**Comment by sspanak** [comment]
I have created #599 for this.
