### ISSUE TITLE
Swap chars that "1", "0", & "#" buttons produce to match keypad printing

### ISSUE THREAD

**Issue by Perifractic** [sspanak/tt9#567]
Firstly thanks for this wonderful app. I'll be featuring it on my YouTube (Retro Recipes) to follow up on a couple of digital minimalism retro phone/flipphone [vids](https://www.youtube.com/playlist?list=PL7QScsJIdNE0mj6EZ4Wdjgnq8sQBNQOLY) I have done recently.

I am using the Kyocera Digno 4 and generally it works well. There's one request that would make this perfect. The physical keypad has characters printed on the keys. Unfortunately these are the opposite of where those characters live in TT9. On the Digno we have:

[1] key: . / @ 
[0] key: - +
[#] key: ` ?

I wonder if there's a way we could have the option to swap which keys produce which characters in TT9. For example, I could move "-" and "+" from [1] so that [0] produces them. And move "@" and "/" from [0] so that [1] produces them. 

As for [#] I realise this swaps entry style but perhaps I could specify long press for "?".

These would make things feel much tidier when using TT9 on phones that already have characters physically printed on the keypad.

Many thanks and keep up the great work.

**Comment by sspanak** [comment]
> Firstly thanks for this wonderful app. I'll be featuring it on my YouTube (Retro Recipes) to follow up on a couple of digital minimalism retro phone/flipphone [vids](https://www.youtube.com/playlist?list=PL7QScsJIdNE0mj6EZ4Wdjgnq8sQBNQOLY) I have done recently.

Awesome, thank you for that!

> I am using the Kyocera Digno 4 and generally it works well. There's one request that would make this perfect. The physical keypad has characters printed on the keys. Unfortunately these are the opposite of where those characters live in TT9...

This almost the same as #498. Once it is completed, everyone will be able to rearrange almost all special characters, even swap them between 0-key and 1-key.

Now, there are some exceptions. I can not move the dot, the apostrophe, the double quotes and the hyphen. In most languages they are part of some dictionary words. For example, in English, there are `rock'n'roll`, `.com`, `fly-by` and whatnot. And since every letter or special character is linked to a number key, moving the aforementioned characters to 0-key, will make it impossible to search for this words in the dictionary. So #498 is the best I can do.

I realize everybody has different preferences. Some like the Samsung layout with ENTER on the `#` key, some prefer the Sony Ericsson layout (I don't even remember it), and you like the Kyocera layout. However, Traditional T9 is meant to mimic the Nokia layout and I have no plans of supporting any other.
