### ISSUE TITLE
Aggressive suggestion of words with apostrophe in Ukrainian

### ISSUE THREAD

**Issue by WallK** [sspanak/tt9#579]
Hello!
When I type a word and want to add a comma after it AND the word happens to be sharing the same key combo as another word that has apostrophe in this place -- I get always suggested this word
This happens surprisingly often!
See video below
**Suggested behavior:**  suggest this apostrophe containing word only if next letter after apostrophe is inputted
In my example -- only after 3 or 9 is pressed (приб'є or приб'ю)
Meaning 56421 should produce "Осіб," (assuming my state of suggestions), 564213 should produce "Приб'є"
I hope I've explained is at least half understandable (: 

**Video:**

https://github.com/user-attachments/assets/101ce488-4013-4b55-b17d-d3f3a344d54f

**Comment by sspanak** [comment]
I understand the problem very well and I've been banging my head for months searching for a solution for typing words with apostrophes.

During the past year, only Ukrainian, but also French and likely Italian and Hebrew, have transitioned from "nearly unusable" to "almost there". There were many problems with English as well. 

Now, as for your problem, you can get "осiб," but you need to scroll back, them forth the suggestion list, them hit 1-key to append the comma. Alternatively, always press OK to accept the current word, before typing the comma. These are the workarounds until I find a solution. 

I believe the actual solution is to: 
1. Always preserve the current suggestion before the next database search. 
2. If there is no exact match for word+1, display the previous word+added punctuation.
3. Otherwise, display the exact match.

**Comment by WallK** [comment]
I do press ok in those cases, but I'm typing too fast to notice sometimes! (: 
Your proposed solution seems like just what will fix our gripes, thank you!
