### ISSUE TITLE
Some word that may be worth adding to dictionaries

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#590]
As mentioned previously (in #472 ), here's a file with some words that you may think are worth to add to dictionaries (english/portuguese).

I'll leave them into you consideration, naturally! (you may not even add anything)

File is in CSV but i've added some descriptions in columns C and D to help you evaluate it.
C, mostly, is the "type" of word and may help you filter what you want to add (if you want to add anything at all)

[tt9-added-words-export--1722510988672.csv](https://github.com/user-attachments/files/16455838/tt9-added-words-export--1722510988672.csv)

You can close this at anytime :)

thank you!!!

**Comment by sspanak** [comment]
Excellent! This is exactly the help I am looking for. I believe all words are good for adding, I just would like to make some corrections:
- gnome - already available in English
- hotmail -> Hotmail
- speccy -> Speccy
- rss -> RSS
- bulling -> did you mean "bullying"? Otherwise, I didn't even know "bulling" exists. Is it really a common word?
- gitlab -> GitLab
- iphone -> iPhone
- olx -> OLX
- suv -> SUV (if you are referring to the big cars)
- You have added Elon to English, but Musk to Portuguese. I'll add the entire name to both languages, in case some part is missing.
- On my side, I found that the name "Al" is missing from English, so I'll add it too.

**Comment by maverick74** [comment]
bulling -> did you mean "bullying"?

yeah, it's "_bullying_"... (i've eat the "Y" at breakfast ahahahaha)

I've added that one wrongly!!! it's already present in english _and_ portuguese, so you can forget about it!

> Is it really a common word?

Yeah... it's pretty _common_ here, now. Almost anything is _bullying_ these days!!! You almost can't say a joke without someone complaining.............. I'm just over 40 but i really feel i did grow up in a completely different world, sometimes!!!

**Comment by sspanak** [comment]
I have added all the English and Portuguese words, including some extra ones that came to my mind, e.g. seeing "Nokia" and "Samsung", I figured out it would be nice to add "Apple", "Xiaomi" and "Huawei", too. They are also extremely popular.

I'll keep the issue and the pull request open until before the release, in case I find more words are missing. It is more convenient to me this way.

> Yeah... it's pretty common here, now. Almost anything is bullying these days!!! You almost can't say a joke without someone complaining.............. I'm just over 40 but i really feel i did grow up in a completely different world, sometimes!!!

I'm just below 40 and I feel the same sometimes. Fortunately, we are still keeping strong on the Balkans and we don't get offended for no reason. At least not all the time.

**Comment by sspanak** [comment]
@maverick74, there is one more thing you could do to help improving Portuguese, if you will. You have used the language a lot, so the word priorities must have improved in comparison to the defaults from Google that I got. If you export them, I will update the main dictionary, so everybody will get better suggestion order right from the start. And this includes you, too, because with the new words you suggested for v37.0, you will have to reload Portuguese, which will reset the priorities to the defaults.

You can export the factory words with their priorities like this:
1. Open the Settings
2. Click the version information to access the Debug Screen.
3. Change the "Log Level" to "Debug".
4. Go to "Languages".
5. Disable all but Portuguese
6. Click the newly appeared "Export Selected". It should be the third option from the top. After exporting is done the CSV will appear either in the "Documents" or the "Download" folder of your phone.
7. Open the file and remove the custom added words at the end. They will probably be around line 643487, after the word "pneumoultramicroscopicossilicovulcanoconiótico". You will recognize them, because they will not conform the ordering by length. This step is not mandatory, I will remove them anyway. Do it only if you are worried about sharing the words publicly.
8. Upload the exported .csv here or send it by e-mail.

After you are done, do not forget to re-enable the languages you were using previously and changing the "Log Level" to "Error" again. Keeping it at "Debug" will cause TT9 to run a bit slower and use a lot of storage space.

Also, note that exporting may take several minutes. It is something like loading a dictionary, but no progress is reported, so will just have to wait a bit for it to finish. You are not required to keep TT9 open, you can do something else on your phone, or even leave it on the table and do other stuff.

**Comment by maverick74** [comment]
sorry, it's a bit late (i know) but there is no hurry either.

I've been away (kind of) and just now was able to the the exported file. i don't seem to find an e-mail address to send it to you...

**Comment by sspanak** [comment]
> i don't seem to find an e-mail address to send it to you...

It's listed on Google Play, but apparently, you are not using it :slightly_smiling_face:. It's ddimo@proton.me. It's also OK, to upload the file here, whatever works for you.

> sorry, it's a bit late (i know) but there is no hurry either.

It's OK, as long as you have exported it before upgrading to v37.0. You still haven't reloaded the dictionary, so the priorities are not reset. And I can include them in any future version, it doesn't have to be 37.0 indeed.

**Comment by maverick74** [comment]
sent.
