### ISSUE TITLE
Search contacts on Cat S22 flip

### ISSUE THREAD

**Issue by AgentGolder** [sspanak/tt9#603]
Hello.
With the recent versions, I can't type letters, (only numbers) on phone's search contacts edit feald and the [#] key doesn't work to change mode.
The problem still persists with the latest version 37.
If I go back to v33, everything goes normally.
Please fix it!
Thanks in advance.

**Comment by sspanak** [comment]
I don't have a CAT S22, so I will need a little help to fix the problem.

Please do the following:
- Go to TT9 Settings.
- Scroll down to the version information and click it. This will open the Debug Options screen.
- Change "Log Level" to "Debug"
- Go to the Contacts app and select the search field. You don't need to type anything there, just make sure the text cursor is in it.
- Go back to the TT9 Debug Options.
- Change "Log Level" to "Error".
- At the bottom, there is a "Recent Log Messages" section. Scroll down a bit, if you don't see it.
- Click or touch the log messages list to copy them.
- Save them to a file. You can do so by pasting them in some text editing app on your phone, or by sending them to yourself in a messaging app, then, saving them to a file on a computer. Do whatever is easier for you.
- Upload the log file here, so I can examine it.

I am interested in the line that looks like this:

```
===> Start Up; packageName: com.google.android.contacts inputType: 524289 actionId: 0 imeOptions: 268435459 privateImeOptions: null extras: null
```

I need to know if instead of `com.google.android.contacts`, it says `org.codeaurora.dialer` or something else. I also need to know the `inputType` and the `imeOptions`.


I realize this may sound difficult, if you don't have technical knowledge, but there is no other way. I need that information for every specific device that fails. You can alternatively make a screenshot of the logs, if it is easier for you.

**Comment by AgentGolder** [comment]
[Log.txt](https://github.com/user-attachments/files/16708541/Log.txt)
Ok, here it is.

**Comment by sspanak** [comment]
This is a regression caused by #538.

@AgentGolder, this is a serious problem, so I'll make an APK with the fix as soon as possible. I just need to know if you have installed TT9 from Google Play or from one of the other sources?

**Comment by AgentGolder** [comment]
From https://github.com/sspanak/tt9/releases/download/v37.0/tt9-v37.0-full.apk.

**Comment by sspanak** [comment]
Excellent! Please try if [v37.2](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v37.2-full.apk) fixes the problem.

**Comment by AgentGolder** [comment]
Has been fixed, thanks for your emediate responce. I'll donate you again at the end of the month.

**Comment by sspanak** [comment]
Sounds great! Thank you for helping make TT9 better.

**Comment by anitalink** [comment]
hello guys. same thing on the mode1 retro ii on the gapps version

**Comment by sspanak** [comment]
@anitalink, doesn't the attached v37.2 solve the problem?

**Comment by anitalink** [comment]
after full reinstalling it`s working perfectly, thank you!
