### ISSUE TITLE
Android TV/ Google TV Support

### ISSUE THREAD

**Issue by hazem-abdelghani** [sspanak/tt9#605]
Please add support for Android TV; it would be great to use your app instead of using a full keyboard on TV.

**Comment by sspanak** [comment]
There are no device restrictions, you can install TT9 on any Android device as long as it runs Android 4.4 or higher and it has enough free space. Unfortunately, I can't guarantee smooth operation on absolutely any TV, because I don't even have one, but it should work on most of them.

What particular problem are you experiencing?

**Comment by hazem-abdelghani** [comment]
First, I'm using the Xiaomi TV Box S (2nd gen), When I try to install the app from the Google Play Store, it shows that the app is not compatible with the device. Then, I tried to install it from F-Droid and successfully loaded the languages, but when I entered the cursor into the text box, only a bar with the word English appeared. Please check the image below:

![20240824_040035](https://github.com/user-attachments/assets/76d16213-a385-4db8-8646-42b4161f5da7)

![20240824_040639](https://github.com/user-attachments/assets/addac85a-e701-4cc3-97e8-05bdc7d76e52)


Another request😅: can I use the keyboard without T9 (only using the layout, like touching key number 2 three times to enter the "C" letter, for example)?

Thank you

**Comment by sspanak** [comment]
> When I try to install the app from the Google Play Store, it shows that the app is not compatible with the device

I see what you mean. This is something Google does on some devices. I have an old Samsung tablet and on it TT9 appears as incompatible, even though it runs a supported Android version. I don't know if I am doing something wrong or the Play Store just decides so for some weird reason, or, in your case, maybe Xiaomi has restricted the allowed apps, because it is a very specialized device. Either way, just use F-droid. The updates may come a bit slower, but they run more security checks and are better all-around, in my opinion.

> when I entered the cursor into the text box, only a bar with the word English appeared

This is normal. TT9 tries to take as little screen space as possible. When it detects a keyboard is connected, it reduces its height automatically (the remote control is a keyboard from technical perspective). You can adjust the layout to your liking from Settings -> Appearance -> Screen Layout.

> Another request😅: can I use the keyboard without T9 (only using the layout, like touching key number 2 three times to enter the "C" letter, for example)?

Sure, you just need to switch to ABC mode using Input Mode key. Go to Settings -> Keypad -> Select Hotkeys and assign some remote key to the Input Mode function, so you can take the control. 

Alternatively, if the Xiaomi supports mouse or emulated touch input, you can enable the full on-screen keypad and click the virtual keyboard key to toggle the modes. 

Also, make sure to check the [Hotkeys section](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#hotkeys) for more info how to control TT9.
