### ISSUE TITLE
ABC mode automatically a capital letter like nokia

### ISSUE THREAD

**Issue by chaimsha** [sspanak/tt9#665]
Two questions.
1. In ABC mode there is no possibility that the first letter is automatically a capital letter, is it possible to add that.
2. There is an option for the user to choose, that in the prediction, the 1 and 0 keys will be like in ABC, that is, that with each additional press on the 1 key, he moves to the next offer, and not like now that in the prediction it is only by the arrows, but with another tap it moves to the symbols, I think that is the best To switch to symbols will be on a star, as in a space.
As in Nokia

Thank you very much

**Comment by sspanak** [comment]
1. Correct, ABC mode provides full control over what you are typing, and it will remain like this. It is extremely important, for example, when typing passwords on other case-sensitive stuff, that the keyboard does not alter what you type. Typing assistance is reserved for Predictive mode, which is focused on typing text with less clicks.
2. I'll answer to each item separately.
    * I've just checked my old Nokia 3310, and it definitely does not work as you described. Multi-pressing the keys cycles the characters only in ABC mode. This includes 1 and 0. I believe mixing the behavior of the keys will be more confusing than it is now. Let's stick with the original.
    * If you don't want to use the DPAD arrows to scroll the suggestions, you can go to Settings -> Keypad -> Hotkeys and configure what function is assigned to what key. You have the absolute freedom to use (almost) any key or disable functions you don't want to use.

**Comment by yh26vh26** [comment]
thanks
As for 1, I didn't convert, obviously because I trusted what I wrote like in Nokia,
And I will explain, the intention was not that if capital letters are activated then it will also be in prediction,
But there will be another option of only the first letter being capitalized, like in Nokia.
That is, there is ABC and there is Abc and there is abc.

It is also possible to add a setting so that those who wish can remove the option of Abc.

As for 2, indeed this is how it is in this Nokia, but in the Nokia C2 / C5 and the like it does work as I wrote.
Anyway, regarding what he wrote that it can be customized, indeed, my intention was that it could be customized, only that the customization only works in normal ABC mode and not in prediction, so please check it again.

Thanks for the keyboard, it's really very good and useful, you just need to add some small things to make it perfect!

**Comment by sspanak** [comment]
I often receive questions like, “Can you make TT9 more like the Nokia C2/Sony Ericsson/Samsung/Touchpal?” or “Can you put the SPACE function on the # key instead of the 0 key?”, etc...

I understand that you may miss your favorite old phones or keyboard apps, but TT9 has its own unique design, inspired by the Nokia 3310 and 6303i. While it captures the feel of the classics, TT9 is its own experience and won’t replicate any specific device exactly.

Thank you for understanding, and I hope you enjoy TT9 for what it is! Please, accept the fact I can not fulfill all wishes by everyone and make it perfect, but only very good and useful.

Second, I will not do it even if you use multiple accounts to draw more attention. This is unacceptable, so please stop doing it or I will ban you from the repo.
