### ISSUE TITLE
Both T9 mode and ABC mode unusable in Deezer app: Keyboard is immediately "reset" after pressing a single key

### ISSUE THREAD

**Issue by ea-ooe** [sspanak/tt9#670]
When typing any text in the Deezer app, only the first letter on each key can be typed because the letters don't stick around for further key-presses. Each key-press is treated as if it were the first letter of a word.

See the attached video for an example:
https://github.com/user-attachments/assets/faee145d-bf9f-4d36-891f-ef272ad69b7c

The same thing will also happen in ABC mode, where a key is immediately interpreted as its first letter, and any further presses will just type that same letter again.

**Comment by sspanak** [comment]
It turns out this is a problem with Deezer that I can not fix entirely on the TT9 side. I have fixed typing, the state is no longer reset, but the words will remain invisible until you press OK or Space to confirm them. See the attached video to get a better idea of what I mean. 

If the Deezer developers decide to enable composing text in that search field, I'll remove the TT9 hack and typing will work normally. It's all up to them. 

Either way, I will include the fix in the upcoming v41.0.

Let this be a future reference for anyone else having problems with searching for artists and songs in Deezer using Traditional T9.

https://github.com/user-attachments/assets/86334465-1577-4727-90f9-6c94c4da87f6

**Comment by ea-ooe** [comment]
Thanks a lot :D
