### ISSUE TITLE
Amazigh language support. 

### ISSUE THREAD

**Issue by abdelhaqueidali** [sspanak/tt9#684]
We need Amazigh to be added. Amazigh has two scripts, its own script and latin script.
Iso code zgh for its original script, and zgh-latn for its latin version.

The number key and the letters it would hold according to the Alphabet order.

Amazigh (Tifinagh)
2 ⴰⴱⴳⴷ
3 ⴹⴻⴼⴽ
4 ⵀⵃⵄⵅ
5 ⵇⵉⵊⵍ
6 ⵎⵏⵓⵔ
7 ⵕⵖⵙⵚ
8 ⵛⵜⵟⵡ
9 ⵢⵣⵥⵯ

Amazigh (Latin)
2 abgd
3 ḍefk
4 hḥɛx
5 qijl
6 mnur
7 ṛɣsṣ
8 ctṭw
9 yzẓʷ

For the dictionaries, they are available here:
https://github.com/abdelhaqueidali/Amazigh-User-Dictionaries
For both Latin and Tifinagh

**Comment by sspanak** [comment]
Thanks for the suggestion!

According to Locale Planet, [zgh](https://www.localeplanet.com/java/zgh/index.html) is the code for "Standard Moroccan Amazigh". Is this the exact language variety we are looking at? I need to know this, because TT9 is written in Java, and in Java I must provide both a language code and a country code for everything to work properly.

One more question, [according to Wikipedia](https://en.wikipedia.org/wiki/Berber_Latin_alphabet), the Latin letter order is standard, meaning A-B-C-D-..., rather than A-B-G-D-... Are you sure you don't want to stick to the standard? It will be much, much easier when one switches from another language to Amazigh. Also, when using a phone with a hardware keypad, the keys will likely be inscribed: "ABC", "DEF", and so on. Inexperienced people will want to use the key inscriptions as a guide, instead of trying to guess the layout you suggested. And when they see different letters coming out, they'll probably get frustrated and give up. I really don't think this layout is such a good idea.

**Comment by abdelhaqueidali** [comment]
Thank you for your respond.
Yes zgh is for Standard Moroccan Amazigh but better call it just Amazigh for shortening it, maybe Amazigh (Morocco) is better in case of adding the country code of Morocco. This Amazigh script is used by all Amazighs whether in standard Amazigh of Morocco or libyan Amazigh or unofficially for Standard Algerian Amazigh. So we use zgh with the name Amazigh. 
The issue of using Amazigh with zgh code is that Amazigh as a whole does not have an iso code, we have it under the name of berber with its code ber but this name is offensive to us. Also using the zgh code is because Standard Moroccan Amazigh is which Amazigh script its official script for Amazigh. Libya does as well following Morocco.

For the latin version, when the standard form is kept, the additional letters that Amazigh has would actually require re-ordering the standard layout. For example key 7 would usually have pqrs, but with the additional letters, it would be pqrṛsṣ while number 5 would keep only jkl. So in this case the standard ordering is not gonna help, it would cause confusion more than if we followed the the order i provided which is just Amazigh script order, and since we are using zgh code we should follow Moroccan standard amazigh which uses that order for latin wven if it is not its official script. 

If you have any more questions I would be happy to help.

**Comment by abdelhaqueidali** [comment]
If we follow the Standard Latin order: 
2 abc
3 dḍef
4 ghḥi
5 jkl
6 mnɛo
7 pqrṛsṣ
8 tṭuɣv
9 wxyzʷ

Here we see that more than 4 letters should be at one place. If we move those additional letters to the next key, the order would become unusual. Trying to move the additional letters somewhere else also would cause the same or greater inconvenient.
But if we follow the first order, it would give four letters four a key based on the standard order of the Amazigh alphabet. So it may seem unnecessary but it will fix this issue of few letters on some keys and lots of letters on others.

Anyway, this is the best i got for now, in case i figure out a more logical way of ordering them better in the standard order, i would inform you. For now, the first order is the best i could come up with.

**Comment by abdelhaqueidali** [comment]
In case of Latin for Amazigh, on Wikipedia, they provide additional letters like ǧ anda č which are meant for dialects, and we would like only the standard ones, since if we want to go to all the addition letters that are not used in the standard, we would go up to 50 letters. Also Tifinagh has more than 50 letters, but only the 31 characters of Tifinagh and their counter part in Latin is what is needed. If anyone is interested in adding a dialect, then it would be practical to create a layout that serves that dialect.

One of the layouts I would like to have is for Kabyle, an Amazigh dialect, it has two additional letters than the standard Amazigh.
Kabyle, iso kab. Country Algeria.
Here is the layout :
2 abcč
3 dḍef
4 gǧhḥi
5 jkl
6 mnɛo
7 qrṛsṣp
8 tṭuɣv
9 wxyzʷ

If you woonder what I mean by Standard Amazigh, it is the Amazigh of Morocco and Libya which use the same script, which is the Amazigh script Tifinagh, the only difference is that Moroccan Amazigh has ⵯ and ⵕ while Libya doesn't. Also, regarding Algerian Latin script we can identify the two additional letters as being regional, as they present two sound ǧ = dj and č = ch.

**Comment by sspanak** [comment]
OK, got it. I don't have any more questions at the moment.

> Note here that I moved letter p to the end for a reason, which is actually not being part of the Amazigh Latin script except for writing foreign words as they are in their original language. The same goes for v.

Have in mind, in Predictive mode, the letters per a key will be reordered based on how often you use them. The alphabetical order is maintained only in ABC mode.

Finally, I would like to point out that I have a long queue of new languages to add, so I can not promise I will include Amazigh in the next version. However, thanks to your clear explanations, I will do it sooner than later. Thank you very much for it!

**Comment by abdelhaqueidali** [comment]
Thank you, just a question, you said that you use country code. So if we consider zgh-ma for Amazigh (Morocco) for the Tifinagh script, what about the Latin one? Cause it would be zgh-latn, wouldn't be there an issue defining the script code instead of the country or is it necessary for the country code? In case of country code being important and not being able to combine language code with script code and country code, you may use the language code tzm plus Moroccan country code. This is Central Atlas Amazigh from Morocco.

**Comment by abdelhaqueidali** [comment]
Thank you for your efforts.

**Comment by sspanak** [comment]
The Latin version should be [this one](https://www.localeplanet.com/dotnet/tzm-Latn-DZ/index.html). The exact country is not important. I just need the two codes to create a Java Locale object and to create a unique language identifier for use here and there in the code.

**Comment by abdelhaqueidali** [comment]
> The Latin version should be [this one](https://www.localeplanet.com/dotnet/tzm-Latn-DZ/index.html). The exact country is not important. I just need the two codes to create a Java Locale object and to create a unique language identifier for use here and there in the code.

tzm-ma is better since ma = morocco, since the letter order is based mainly on Standard Moroccan Amazigh. tzm is a code for a Moroccan Anazigh dialect, so using it there in that source for Algeria is just a solution to provide Amazigh latin script.

my suggestion in case of language code with the country code: 
zgh-MA for standard Moroccan Amazigh Tifinagh based script
tzm-MA for Standard Moroccan Amazigh latin based script

My suggestions in case of language code with the script code: 
zgh-Tfng for Tifinagh
zgh-Latn for the Latin one

Language codes for Amazigh are used differently just to solve the issue of not having a unique iso code for all Amazighs on all platforms.

**Comment by abdelhaqueidali** [comment]
Just to sum up my proposal and some details:

LANGUAGE CODES
*For Amazigh with Tifinagh script*
Amazigh name: ⵜⴰⵎⴰⵣⵉⵖⵜ
English name: Amazigh
Language Code: zgh-MA
*It doesn't need specifying the name of the script in the language name.

*For Amazigh with latin script*
Amazigh name: Tamaziɣt
Engliah name: Amazigh (Latin)
Language Code: tzm-MA


*DICTIONARIES*
I have updated the user dictionaries at:
https://github.com/abdelhaqueidali/Amazigh-User-Dictionaries
Amazigh (Tifinagh).txt
Amazigh (Latin).txt

**Comment by sspanak** [comment]
A language can only have one name. Since I have already used "Português / BR" and "Português / PT" for Brazilian and European Portuguese, for consistency, I'll probably use a similar naming scheme, e.g. "Tamaziɣt / MA". And as for the name in Tifinagh, I think "ⵜⴰⵎⴰⵣⵉⵖⵜ" should be clear enough. But don't worry about the locales, I got this.

One more question comes up to my mind. What kind of quote marks do you use? Currently TT9 supports several standards, English: `"quoted phrase"`, German: `„quoted phrase“`, and French: `«quoted phrase»`. Please, let me know which one to use. 

Also, from what I read there are no other special punctuation marks, correct? If there are, please let me know, so that I can include them.

> I have updated the user dictionaries...

I will use the latest version when I start working on this. In the future, feel free to suggest more words or even open a pull request to add them directly.

**Comment by abdelhaqueidali** [comment]
> Currently TT9 supports several standards, English: `"quoted phrase"`, German: `„quoted phrase“`, and French: `«quoted phrase»`.

We use the same as in English, and you are correct, there are no other special punctuation marks.

**Comment by sspanak** [comment]
I have went throught the dictionaries from your repo and I have found the following issues:

- Tifinagh Variant:
  1. There are a lot of repeated words. I removed them.
  2. There is one, possibly invalid word: "ⵉⵙⵒⴽⵍ". The letter "ⵒ" is not available in the layout, so it is not possible to include this word in the dictionary. If the word is valid, we must put "ⵒ" on some key. If so, please, let me know where it belongs
- Latin Variant:
  1. Again, there are a lot of repeated words that I removed.
  2. The letter "ẓ" was missing from the layout. I have added it to the 9-key.
  3. There is a word containing the same missing letter "ⵒ", "isⵒkl". I suppose, it is the same word as above. In this case, it is simply incorrect, the Latin equivalent must be used here.
  4. All words are in lowercase. I am unsure if you delibaretely converted all words to lowercase or the word list contains no names, but this means Automatic Capitalization feature will not work. Just so you know.
  5. Tifinagh is unusable on Android 5, because it has no appropriate fonts (see the screenshots). I don't have access to all my testing devices at the moment, but I suppose it will be the same at least until up to Android 8. This does not affect TT9, it will function correctly. It will suggest words and put them in the applications, and, if you are sending a message, they will be able to read it on the other side. It's just a visual problem. Anyway, I suppose, people who want to use Tifinagh would have installed all necessary fonts manually. I don't think we should do anything about that.

Other than the above, it all looks OK. I will include the language in the next version.

Android 5 screenshots:
![missing](https://github.com/user-attachments/assets/56ec3b21-2249-4225-9adb-7347c461efe7)
![missing2](https://github.com/user-attachments/assets/3a2429f8-dec8-4257-8117-2a5fa2b47c06)

**Comment by abdelhaqueidali** [comment]
> wxyzʷ

yes, letter ẓ should be added after letter z

**Comment by abdelhaqueidali** [comment]
> 1. There are a lot of repeated words. I removed them.

yes, I didn't do a sort process to clean it.

**Comment by abdelhaqueidali** [comment]
The word with the letter ⵒ should not be there, better be removed.

letters ⵒ and ⵠ which represent p and v accordingly are not used in the standard form but I believe we should add them as well.

Letter ẓ is supposed to have been added by me on the key number 9 so it contains [xxyzẓʷ], I missed it.

We usually install some font on Amdroid 5 to fix this issue, I had it back in 2017 and that what we used to do.

Words being all lower cased is not a problem but I believe that T9 should be able to capitalize when needed. for example capitalizing first letter of a word after a full stop.
The list doesn't have names which need capital letter at furst, they just words like verbs, nouns, prepositions.. etc

**Comment by sspanak** [comment]
> Words being all lower cased is not a problem but I believe that T9 should be able to capitalize when needed but if not, it's ok. Because in Amazigh, in latin, first word in the sentence should be capitalized, just lile in English. So providing a capitalized version meaning duplicating those words with their first letter capitalized.
The list doesn't have names, they are just words like verbs, nouns, prepositions.. etc

Ok, so, I didn't explain myself clear enough. I was talking about proper names indeed, but since there are none, we're all good. Capitalization at the beginning of sentences will work.

> The dictionaries still needs work, I may add names and I would make sure first letter is capitalized in thr latin version.

This will be very useful. When using a T9 keyboard typing any word outside the dictionary is very slow. People will definitiely want to type city names, landmark object names, their personal names, so when you add them, feel free to ping me.

> Thank you for your effort. I appreciate it.

No problem. You made if very easy for me, so I decided to complete the task as soon as possible.

Final questions about the Latin layout. In almost all other languages, similar sounds, represented using "special" letters share the same key. Following this thought, doesn't it make more sense to put "Ɣ" next to "G" and "H" on 4, instead of being next to the entirely different "T", "U" and "V" on 8.

Also, isn't it more logical to put "Ɛ" on 7 instead of on 6? As I understand the sound is somewhat similar to "R" (which is on 7), and has nothing in common with "M", "N" or "O" (on 6). Or, depending how you see it, it could be on 4, sharing similarity with "Ḥ".

If you are concerned that there will be too many letters on a single key, don't worry. It is the same in French, Portuguese, Czech and others. Typing still works quite well.

**Comment by abdelhaqueidali** [comment]
> "Ɣ" next to "G" and "H" on 4,

I put "ɣ" there cause usually old fonts and keyboards use letter "v" or its place for letter "ɣ". also it would make the number of letters for each key almost the same, 4 essential letters for key. putting "ɣ" with "g" would make it five letters.
Not sure which one is better.

**Comment by abdelhaqueidali** [comment]
> "Ɛ" on 7 instead

the same for ɛ, on keybiards and old fonts, it is used for letter "o" or its place.

I based this order for those letters based on what is common on phones and computers, their keyboard and old fonts usage. as well as taking into consideration the number of letters for each key, so my prposal doesn't put much letters in one key.

**Comment by sspanak** [comment]
Alright, let's keep the current layout. You seem to know your stuff.

Here is [v42.4](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v42.4.apk) for you to test. Please, let me know if you find any issues. Otherwise, this is what I will include in the upcoming v43.0.

**Comment by abdelhaqueidali** [comment]
I tested it, Every seems to be good. Thank you.
