### ISSUE TITLE
Add optional voice input software button

### ISSUE THREAD

**Issue by TomJansen** [sspanak/tt9#83]
Hi. It would be really handy if there was a voice button which made use of a voice keyboard backend, just like florisboard does. To my knowledge, florisboard does not have it's own speech to text engine, but makes use of other voice keyboards that are installed. This would obviously be really handy for us T9 users.

**Comment by sspanak** [comment]
This should be possible. Currently, everything is designed around texting, but I guess, adding a `VoiceHandler`, besides the `KeyPadHandler` and the `SoftKeyHandler` would do the trick. It would require refactoring some more code, of course. And as for the button, it can take the place of the current "OK" soft key. Personally, I don't find myself using it at all, because it is the same as the Center key on the keypad...

All in all, this may be a good idea, but unfortunatelly, I can't promise I'll do it anytime soon. I have no idea how to do it, so I need to spend some time in research. The thing is, I won't have so much free time after the end of October, so... who knows.

**Comment by TomJansen** [comment]
Maybe it is good to, when the setting is enabled, add an extra button next to the OK button containing a Microphone icon, which when tapped switches to a Voice IME?

>because it is the same as the Center key on the keypad
How do you mean? I do not have a dedicated button for switching to Voice IME (Qin F21 Pro)

**Comment by sspanak** [comment]
I could be an extra button, yes. I can't imagine what's the best option right now.

> How do you mean? I do not have a dedicated button for switching to Voice IME (Qin F21 Pro)

No, no, it's the other way around. :slightly_smiling_face: 

My point is I always use the physical OK key (the DPAD center key), instead of the on-screen OK. So, from my perspective, the on-screen OK is useless and only takes up precious screen space that could be used for something else, for example a voice input button.

Btw, a side question: are all keys of your phone working well? I have the Pro Plus version and the 4-, 8- and *-keys must be pressed either very hard or several times to work. 6 and 7 are somewhat better, but definitely not optimal.

**Comment by sspanak** [comment]
So, holding OK may be a good idea. This is how they do it in the new KaiOS phones. Also, this is kind of a safe choice, because all phones would have it, not only the F21 Pro.

Anyway, I am not sure how much free time I would have in the future, so if you do, please, go ahead and research this feature. Same goes for [postpersonality](https://github.com/postpersonality), whom I can't ping here.

If any of you guys find a way to integrate voice input without refactoring the entire project, it would be great.

**Comment by sspanak** [comment]
> I have degoogled phone but I'll see what I can do.

That's an important thing to consider. It has to be a freely available service, that provides enough usage quota, and that has a compatible license.

**Comment by TomJansen** [comment]
Florisboard does this by a button that is completely independent from the voice IME. You can choose your own voice IME. See https://github.com/florisboard/florisboard/pull/1587

**Comment by sspanak** [comment]
Actually, Android may support voice input natively using the [SpeechRecognizer](https://developer.android.com/reference/android/speech/SpeechRecognizer) class. This is probably the easiest way to go.

**Comment by nebkrid** [comment]
Hi, there is even an easier way of using speech input than implementation of speech recognizer if you are ok that the speech recognition app is in foreground when listening. The main thing is to send an intent with RecognizerIntent.ACTION_RECOGNIZE_SPEECH in startActivityFor result. See here: https://developer.android.com/training/wearables/user-input/voice#java

**Comment by sspanak** [comment]
I wish I could do that, but unfortunately, it is not possible, because `TraditionalT9` main class extends `InputMethodService` and `startActivityForResult()` is not available in services.

**Comment by nebkrid** [comment]
oh, I didn't know that this is not available...
However there is a second method, which is slightly more effort than the intent approach as it needs the Audio-Permission and its own implementation of user feedback. But if you are interested in, here some hints:
Basically you need a [SpeechRecognizer](https://developer.android.com/reference/android/speech/SpeechRecognizer#createSpeechRecognizer(android.content.Context))
```
SpeechRecognizer speechRecognizer = SpeechRecognizer.createSpeechRecognizer(context)
speechRecognizer.setRecognitionListener(yourListener);
//and then start listening with
speechRecognizer.startListening(RecognizerIntent);
```

**Comment by guillaumebaeriswyl** [comment]
Just wanted to say thank you for this amazing keyboard and to add a +1 on this request ! for me it's the only thing missing !

**Comment by sspanak** [comment]
> Just wanted to say thank you for this amazing keyboard and to add a +1 on this request ! for me it's the only thing missing !

Thank you for the good words. I am trying to get to this...

**Comment by yant0** [comment]
question will it be a on screen button too?
I have a device which does not have a touch screen so the whole d pad including the OK button is used for mouse simulation so it might not be possible for me to do a hold on the OK button since it already does not support cycling through the letters with the d pad

**Comment by felipecrs** [comment]
Just chiming in to say that this would be a super useful feature for my dad, to help him "write" messages on WhatsApp.

**Comment by joddsus** [comment]
Doesn't whatsapp already have a microphone button?

**Comment by felipecrs** [comment]
That's for sending voice messages, which is not the same thing as text messages typed by voice. :)

**Comment by joddsus** [comment]
I just realized after sending the reply, never used it before.

**Comment by sspanak** [comment]
I do understand this is a much desired feature, but I simply don't have enough time to get to it...

**Comment by felipecrs** [comment]
I'd recommend keeping this open, even if it's not going to be closed soon.

**Comment by TomJansen** [comment]
I agree with this. I don't see why it is good to close stale issues, it does not make them solved when an issue is closed.

**Comment by sspanak** [comment]
Agreed. I have changed the rules for stale issues. Now the bot will only close the ones with "wontfix" and "invalid" labels.

**Comment by Pbeight** [comment]
> I also remapped the menu key now so that when I long press, I switch to the Google Voice IME. This seems to work really well. Maybe I can remap the menu key further (via magisk or something) so that it can be used as a backspace key when I short press it, but I am not sure. The menu key is kinda useless anyway. This would reduce the need for software keys even further, even making the software keys useless for me.
How did you remap the menu key?

**Comment by TomJansen** [comment]
I used the app Key Mapper by sds100 on Google Play

**Comment by Pbeight** [comment]
Hmm I considered using that, but I would prefer not to have an extra
service running all the time.

I attempted to rename the menu key in system/usr/keylayout, but I couldn't
find keycode 82, which is what the App "keyevent display" says it is.

In any event, how did you set it the Google voice ime?

**Comment by hoagiesfortune** [comment]
I'm late to the conversation here, but I wanted to chime in and request this feature as well. I think it is the last element that would make it perfect! The app is otherwise great, appreciate the time and effort spent.

**Comment by sspanak** [comment]
You are not late for the party. I have not rejected this feature. Unfortunately, there is still much work on what is most important for a keyboard - typing, so I am still focused on that. And... I only have two hands... :slightly_smiling_face:
