### ISSUE TITLE
Get suggestions from multiple languages / quickly change between languages

### ISSUE THREAD

**Issue by TomJansen** [sspanak/tt9#85]
In the options menu, there is a possibility to import multiple languages. However, when typing in predictive mode, only suggestions from one language are given. Not sure if this has something to do with issue #24.

It would be nice if sugesstions from multiple language dictionaries were combined, or if there was a quick way to change the language without going to the settings and importing the dictionary again, like with the # key: 1. 123 mode, 2. abc mode, 3. Predictive mode language A, 4. Predictive mode language B, etc (which would be my preference).

**Comment by sspanak** [comment]
@TomJansen, there is indeed a way of changing the language with "#". Just hold it. 

Actually, TT9 provides a lot of control over typing, similar to old Nokia phones. You may want to check out [the manual](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#hotkeys) for all the possible hotkey options.

As for providing suggestions in all languages simultaneously, I don't think it is a good idea, due to:
1. It will be very confusing, especially when the languages use different alphabets.
2. Due to performance reasons, the number of exact suggestions is limited to 8 and the similar words are limited to 20. If suggestions from many languages are displayed, you will actually see only a few words from each language. 
3. In fact, if you use one language A a lot and language B only occasionally, you would not get suggestions from language B, because the words are displayed based on the frequency of use.

I hope this helps!

**Comment by TomJansen** [comment]
Oh wow thanks for the suggestion that holding the # key changes languages. I read over that in the manual!
